### ISSUE TITLE
[Suggestion] Index folders recursively (but not files?)

### ISSUE THREAD

**Issue by blzq** [kupferlauncher/kupfer#100]
It would be nice if Kupfer could recursively index the directories within the folder catalog, maybe not including files in the index as it might become too slow.

**Comment by SanskritFritz** [comment]
Kupfer does follow the subdirectories. Maybe give us an example of what you meant?

**Comment by blzq** [comment]
For example, when there's a path `/dir/subdir/subsubdir/file.txt`, it seems that if `dir` is in the catalog, `dir` and `subdir` are accessible from the top level, but not `subsubdir`.

**Comment by Zarnaik** [comment]
I also want this. As an ex-gnome-do user I'd also like to have the files available though. Perhaps make an option for it?

**Comment by khurshid-alam** [comment]
Use recursive directory plugin: https://github.com/skpdvdd/KupferRecursiveDirectories

Also if you enable yt can search any file or folder.

**Comment by egslava** [comment]
The plugin seems to be outdated and doesn't really work :( The app itself doesn't look throw subdirectories as well. So, currently, I don't understand what to do :'(

**Comment by egslava** [comment]
Fixed it. Though, it seems, it doesn't use a recursive search for files :(

**Comment by thomas-mc-work** [comment]
Try out `deepdirectories` which was part of [my closed PR #115 ](https://github.com/kupferlauncher/kupfer/pull/115). It's adapted to the latest kupfer version and working great. And btw. without any performance regressions.

**Comment by KarolBedkowski** [comment]
Close due inactivity. Plugin deepdirectories solve this problem.
