### ISSUE TITLE
Suggestion: Show dropdown on launch

### ISSUE THREAD

**Issue by sproclavism** [kupferlauncher/kupfer#101]
It would be nice if an option was added to always expand the dropdown menu when Kupfer is launched.
The dropdown would always stay open, even if you hit backspace.

**Comment by KarolBedkowski** [comment]
I don't see any value to always show this list. First, this will be hard to implement - actually there are 3 separated list for 3 panes and we show/hide/refresh one depending on current state. Second, show list require load some leaves; Kupfer try to load data incrementally, so this may slowdown it.

As always, PR will be welcomed.
