### ISSUE TITLE
"Show with selection" stopped working

### ISSUE THREAD

**Issue by hetdegon** [kupferlauncher/kupfer#103]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: 319
Window Manager: Kwin5
Desktop Environment: KDE Plasma 5
Linux Distribution: Ubuntu 17.10

### Actual Behaviour
Selected text won't display on Kupfer anymore when invoking it with "show with selection"'s shortcut

### Expected Behaviour
Selected text should be already set.

Not much more to say, it just stopped working altogether.

**Comment by bluss** [comment]
Hi, is the clipboard plugin enabled? No special settings in the plugin is needed, just needs to be enabled. Can you find the clipboards catalog and its selection object inside?

**Comment by hetdegon** [comment]
Oh, I apparently disabled it at some point! Re-enabling it made show with selection work again.
