### ISSUE TITLE
Firefox keywords is empty

### ISSUE THREAD

**Issue by ronnac** [kupferlauncher/kupfer#104]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v319
Window Manager:LXDE
Desktop Environment:LUBUNTU
Linux Distribution:Artful Aardvark

### Actual Behaviour
I am having trouble figuring out how the firefox keyword plugin works.
I launch kupfer.  The firefox keyword plugin is checked.
Test1: I enter ?hello <return>: this gives me a little pop-up in the upper right corner of the screen with the Kupfer logo and the text "?hello" 
Test2: I type ?hello <tab> search with, : The 3rd icon says "Firefox Keywords is empty"

### Expected Behaviour
I don't know. I couldn't find any documentation of this plugin.

**Comment by KarolBedkowski** [comment]
Almost all plugins work in this same way.
If Firefox plugin is not checked in Preferences -> Catalog you must first of all find Firefox (type firefox), "enter" to it (push right key) and you should find bookmarks etc.
If Firefox plugin is checked in Catalog -> all bookmarks should be visible in main list, so entering part of name should select it.
