### ISSUE TITLE
Open in current window (instance)

### ISSUE THREAD

**Issue by xididri** [kupferlauncher/kupfer#105]
I just started using Kupfer, I read the kupfer [help](https://kupferlauncher.github.io/help/en/) and the [FAQ](https://github.com/kupferlauncher/kupfer/wiki/FAQ) but I don't find a way to open a folder or a file in the current instance of an already running app.

For example, while nautilus is running, I type "Downloads" and I would like to open a new tab in Nautilus to the ~/Downloads folder, but no action allows it. It always open a new instance. Even the action "Reveal" does open a new instance.

Another example : I type "Firefox" and I would like to reveal the already running Firefox app.

Or if 2 Firefox instances are running and I type "google.com", I would like it to have the choice to choose in which ones of the instances the page will open (as a new tab).

**Comment by khurshid-alam** [comment]
Nautilus had feature to always open folders as new tabs. But that was removed. Kupfer doesn't do anything extra, it just executes org.gnome.nautilus.desktop file. That's all. If you want that particular behavior, the file a bug against Nautilus to have that feature as a desktop action.

**Comment by KarolBedkowski** [comment]
Closing due inactivity; Fill free to reopen if necessary.
