### ISSUE TITLE
Kupfer not opening in KDE

### ISSUE THREAD

**Issue by ardydo** [kupferlauncher/kupfer#106]
### Environment

Kupfer Version: v208
Window Manager: Kwin
Desktop Environment: KDE
Linux Distribution: Kubuntu 17.10

### Actual Behaviour

Kupfer doesn't start when launched from any kind of launcher. It does launch, however, when launched from terminal. 

### Expected Behaviour

When running from any launcher, Kupfer should start as usual.

### Extra information

This is a screenshot from the task manager. The two processes stuck at 68k memory are what happen when I try launching Kupfer normaly and the rest is when it's ran from a terminal
![image](https://user-images.githubusercontent.com/14042262/36458676-d3aa7ac8-168e-11e8-9b64-e8193e642f18.png)

I tried several approaches (making a .sh file, runing it on startup, with alt+f2 and etc) but the only thing that works is running it from the terminal itself.

I'm also quite certain that it's KDE because I've tried running another DE (XFCE) and kupfer starts on it like it should.

**Comment by SanskritFritz** [comment]
This was fixed in #72 
I really recommend using Kupfer 3.

**Comment by ardydo** [comment]
Oh, wow.

I've been running the distro packages and came all the way here to the repository and didn't even check the version. Totally my bad.

Thank you for the swift response!
