### ISSUE TITLE
Plugin for  pidgin don't show contacts

### ISSUE THREAD

**Issue by a11g0rhythm** [kupferlauncher/kupfer#107]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: **master from git -> Latest commit 2b306a2 on 23 Apr 2017**
Window Manager:  **Compiz**
Desktop Environment: **Mate 1.18**
Linux Distribution: **Ubuntu Mate 17.10**
Pidgin 2.10.12 (libpurple 2.12.0)
active pidgin plugin with option show offline contacts

### Actual Behaviour

Contacts from pidgin don't show

### Expected Behaviour

Kupfer shows contacts from pidgin

**Comment by khurshid-alam** [comment]
You need to start [idgin first then restart kupfer.

**Comment by benkinooby** [comment]
I have the same issue too.
Pidgin: 2.12.0
libpurple: 2.12.0

"Pidgin Contacts" shows an empty list.
"Pidgin Internet Messenger Documents" works as expected and shows files I sent over pidgin.

Starting pidgin, and then restarting kupfer did not help me.

**Comment by SanskritFritz** [comment]
There must be something in the environment, because it work perfectly here. I use Plasma 5 on Archlinux.

**Comment by a11g0rhythm** [comment]
ubuntu 20.04
kupfer from this repository
pidgin plugin enabled
log from kupfer --debug
....
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21173
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 20662
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21817
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21180
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21565
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 20543
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 20802
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21068
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21838
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 20438
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21733
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21628
D [kupfer.plugin.pidgin] ContactsSource: updating buddy 21502
....
but there is no contact to display

**Comment by KarolBedkowski** [comment]
I don't see any problem with last Kupfer and Pidgin 2.13.0.
If you don't select Pidgin in "Inclusion in Top Level Search" contacts are located only after selecting Pidgin and press right arrow. 
Offline contact are only visible after checked appropriate option.

**Comment by a11g0rhythm** [comment]
@KarolBedkowski 
Clean installation of ubuntu 20.04 in vm
kupfer 319 from repo
kupfer 2 from https://github.com/KarolBedkowski/kupfer-adds
Synapse from repo

![pidgin](https://user-images.githubusercontent.com/1868730/83532406-7e846900-a4ee-11ea-8049-a0c7c19a0bd4.png)
![versja](https://user-images.githubusercontent.com/1868730/83532192-35341980-a4ee-11ea-9273-18cbc9b5dc4c.png)
![kupf_319_pidgin](https://user-images.githubusercontent.com/1868730/83532208-39f8cd80-a4ee-11ea-9d59-b00ceddca2ca.png)
![kupf_319_pidgin_blank](https://user-images.githubusercontent.com/1868730/83532224-3d8c5480-a4ee-11ea-89a1-12daabb821b6.png)
![kupf_2_ver](https://user-images.githubusercontent.com/1868730/83532248-454bf900-a4ee-11ea-9660-eff933565a65.png)
![kupf_2_pidgin](https://user-images.githubusercontent.com/1868730/83532316-5f85d700-a4ee-11ea-9130-084496a3cdcc.png)
![synapse](https://user-images.githubusercontent.com/1868730/83532755-ff436500-a4ee-11ea-940b-6cf08f54b856.png)

**Comment by KarolBedkowski** [comment]
Can't replicate this problem.
Last version of Kupfer and Pidgin 2.14.12 (libpurple 2.14.12) works fine.
