### ISSUE TITLE
Launcher window does not close automatically after executing the action

### ISSUE THREAD

**Issue by nanawel** [kupferlauncher/kupfer#108]
### Environment

Kupfer Version: 319 (distro package 319-2)
Window Manager: Xfwm
Desktop Environment: Xfce
Linux Distribution: Arch

### Actual Behaviour

Type the hotkey to bring the launcher window up front. Type an action (for example "geany" to run the text editor), then press Enter.

The action is executed, but the launcher window stays on top.  You have to select it with the mouse, then press Esc twice to make it disappear.

### Expected Behaviour

After executing the command, the window launcher should disappear automatically, like it used to do in earlier versions.

**Comment by SanskritFritz** [comment]
Kupfer closes itself, when it loses focus. Maybe your xfce is set up in a way that it prevents focus stealing? Does geany appear with the keyboard focus on it, or are you still in kupfer?

**Comment by nanawel** [comment]
Yes Geany has the keyboard focus once it's launched. If I type anything after pressing Enter, it goes in Geany text editor. Strange!

**Comment by nanawel** [comment]
That seems to do the trick! :+1:

**Comment by SanskritFritz** [comment]
> Edit: Nope I can't. No previous version is available in the repo :(

You're on Archlinux, so see here: https://wiki.archlinux.org/index.php/Arch_Linux_Archive#How_to_downgrade_one_package
But that is not necessary after all, just wanted you to know.

**Comment by nanawel** [comment]
Yeah I use the `downgrade` command provided by the [AUR package with the same name](https://aur.archlinux.org/packages/downgrade/) but it gave me no other version.

**Comment by nanawel** [comment]
Unfortunately it does not seem to really fix the issue. Today after rebooting my system I can still randomly reproduce it.
In order to close the launcher I have to click on it, then click somewhere else, which confirms the focus issue. This problem was not present some weeks ago, so I'm wondering it it has somethin to do with Kupfer or the window manager (but I think it has not been updated for months).

**Comment by KarolBedkowski** [comment]
Probably not relevant anymore.
