### ISSUE TITLE
add index of system settings

### ISSUE THREAD

**Issue by aster94** [kupferlauncher/kupfer#109]
hello,

the system settings (session, about me, display, network, keyboard, ecc) are not indexed in kupfer
there is a workaround to do it: https://askubuntu.com/questions/471655/how-to-index-system-setting-in-kupfer  
but i would ask if it is possible to automatically add it by default (of better with a plugin)

### Environment

Kupfer Version: 209
Window Manager: xfwm
Desktop Environment:xfce
Linux Distribution:xubuntu 17.10

p.s:  i would like to ask also if there is a way to don't use a shortcut to start kupfer. i mean i would like that when i start typing in my desktop it automatically start kupfer

**Comment by khurshid-alam** [comment]
Gnome disabled individual system settings desktop files. But Unity still has it.So it works for Unity. By default kupfer search & index all desktop files respecting `OnlyShowIn` parameter.

**Comment by KarolBedkowski** [comment]
Desktop environment can be changed in preferences. Filtering may be disabled by "Use Desktop Filter" checkbox.
Kupfer don't show applications with NoDisplay.
