### ISSUE TITLE
how to exclude specific (or just hidden) folders?

### ISSUE THREAD

**Issue by cedardocster** [kupferlauncher/kupfer#113]
### Environment

Kupfer Version:319
Window Manager:whatever ubuntu 18.04 comes with
Desktop Environment:gnome
Linux Distribution:Ubuntu 18.04

### Actual Behaviour
searching for files, the first suggestions are from hidden folders I don't want to search (e.g. lots from ~/.local/share/trash/files etc, but other hidden folders as well.  Takes a long time to scroll down to the meaningful locations

### Expected Behaviour
somehow be able to exclude all hidden folders or have a black list of folders to exclude in the catalog area

**Comment by khurshid-alam** [comment]
It's weird. Documents plugin enabled only recent files and bookmarks at the top of the search tree. May be you have tracker plugin enabled? Also try clearing the cache (~/.cache/kupfer) and then restart kupfer.

**Comment by KarolBedkowski** [comment]
Not related to Kupfer; locate cache file list in it's database and can be updated by `updatedb` command. Limiting locate is possible by updatedb configuration.
