### ISSUE TITLE
feature request: switch to locate

### ISSUE THREAD

**Issue by cedardocster** [kupferlauncher/kupfer#114]
### Environment

Kupfer Version:319
Window Manager:gnome default
Desktop Environment:gnome
Linux Distribution:Ubuntu 18.04

### Actual Behaviour
when scrolling through results, there's no way to quickly turn original search term into a "locate" request.  If you are 10 items down and decide to locate by hitting tab, if there's an option to locate it'll be using the term at that 10th item, not the original term

### Expected Behaviour
during a search pressing some key combination would immediately do a locate (i.e. using the locate plugin) search on that original search term (not the term at where-ever you're at at the moment)

**Comment by khurshid-alam** [comment]
Not sure I understand. Kupfer doesn't automatically scroll down search-items. You do that yourself. Which means when you select an item you are explicitly telling kupfer to perform action based on your selected item. No? If you want kupfer to perform action on the first search object, then don't scroll down just perform the action.

It's very basic. You can't contradict yourself and expect kupfer to work on it's own.

However kufer could define a default object and assign a shortcut key for that object. I don't know if it's possible in the current setup.

**Comment by cedardocster** [comment]
The reason you'd want to switch to a locate search while having scrolled down in the original list would be because the thing you're looking for wasn't found the normal way.  Currently you have to escape and enter "." and retype the term if the locate option doesn't appear at the bottom of the list (which can be quite long).  I guess another way of stating this request would be to have a way to turn an already typed in entry into a "." entry without having to retype the term (e.g. maybe by "alt-." or something similar)  That would be handy!!
