### ISSUE TITLE
Selected text is not refreshed when recalling kupfer

### ISSUE THREAD

**Issue by fdev31** [kupferlauncher/kupfer#118]
Symbolic actions are expected to be "up to date" when calling kupfer while they are not.

If being repeatable is a strong feature, then I couldn't find any way to refresh the context explicitly.

### Environment

Kupfer Version: kupfer v319
Window Manager: awesome
Desktop Environment: mate
Linux Distribution: archlinux

### Actual Behaviour

When calling kupfer it starts with the "last action", if this action is symbolic (say "selected text") the content of the last time the action was triggered is displayed.

Eg. 
1. "Selected text" > "Search on wikipedia"
2. [ENTER]
3. [select another text]
4. [call kupfer]
5. [ENTER]
6. The two open wikipedia pages are showing the same first selected text

### Expected Behaviour

1. "Selected text" > "Search on wikipedia"
2. [ENTER]
3. [select another text]
4. [call kupfer]
5. [ENTER]
6. The two open wikipedia pages are different, showing the selected text at the time the action was done

**Comment by KarolBedkowski** [comment]
I don't see error here.

There two methods to call Kupfer. "Show Main Interface" and "Show with Selection" (see preferences for your binding).
When you call Kupfer by "Show Main Interface" always is selected last showed item. You can go to current "selected text" by pressing "Select selected text" binding (ctrl-g by default).
