### ISSUE TITLE
Sudo plugin giving TypeError: activate() got an unexpected keyword argument 'ctx'

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#120]
Hi,

I was using sudo plugin from [here](https://github.com/tuxcanfly/kupfer-plugins/blob/master/sudo.py), from the source codfe I couldn't find anything that can cause this type of error. So may be a error on kuper side ? It was working few version before.

Full log:

```
Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer/ui/browser.py", line 1849, in _activate
    self.data_controller.activate(ui_ctx=self._make_gui_ctx())
  File "/usr/share/kupfer/kupfer/core/data.py", line 811, in activate
    res, ret = ctx.run(leaf, action, sobject, ui_ctx=ui_ctx)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 327, in run
    ret = activate_action(execution_token, obj, action, iobj)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 81, in activate_action
    return _activate_action_single(obj, action, iobj, kwargs)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 89, in _activate_action_single
    ret = action.activate(obj, **kwargs)
TypeError: activate() got an unexpected keyword argument 'ctx'
```

### Environment

Kupfer Version:310
Window Manager: Compiz
Desktop Environment: Unity
Linux Distribution: Ubuntu 19.04

**Comment by KarolBedkowski** [comment]
Hi,
activate method in Open class has definition:
def activate(self, leaf, ctx):

So activate method OpenAsRoot should also have ctx parameter.

**Comment by khurshid-alam** [comment]
Yes, I realized now, `def activate(self, leaf, ctx=None):` & `def activate_multiple(self, objects, ctx):` does indeed works. Also I have now converted into Action class since action_accelerator doesn't really work with Open (also ported to python 3).

Thanks.
