### ISSUE TITLE
Go to action for HostLeaf or FileLeaf

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#123]
It would be nice if we can have `go to` action for HostLeaf and possibly other objects (FileLeaf ?). We could use [BAMF](http://lazka.github.io/pgi-docs/#Bamf-3) window matching (which is based on libwnck Or libwnck which is being used for ApplicationLeaf) library for it. Mate/Unity/Xfce already uses it in hud like application. 

The workflow will be like this:
1) User opens a ssh connection with terminal
2) Next time user types the same host name it shows "**Go to"** as default action and "**Launch Again**" below it just like it does for an appleaf.

Thoughts ?

@bluss @KarolBedkowski

**Comment by KarolBedkowski** [comment]
Idea is ok, but I not sure how this may be implemented.
Some example needed...

**Comment by KarolBedkowski** [comment]
Since v322 Kupfer remember last action activated for each leave and boost score for it. Usually this action will be first choice for this (exact) leaf. Also minor bonus is added for action and this same leaves type.
