### ISSUE TITLE
BUG: launching applications when VLC is running

### ISSUE THREAD

**Issue by sedessap** [kupferlauncher/kupfer#124]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v319
Window Manager: LXDE
Desktop Environment: LXDM
Linux Distribution: Arch Linux (updated on the same day as this issue's date). This behaviour happens on more than one machine.

### Actual Behaviour
1. This only happens when VLC is launched. So launch VLC first.
2. Activate kupfer; type one of either two applications' names: **keepassxc** or **virtualbox**
3. Press Enter.
4. The chosen program doesn't launch. Instead, VLC window is activated and brought to the foreground.

### Expected Behaviour
After (3) kupfer should launch either **keepassxc** or **virtualbox**.

**Comment by KarolBedkowski** [comment]
I can't reproduce this behavior.
1. please check last version from GH
2. please check is gi.wnck is intalled / available
3. please attach some logs when Kupfer is running in debug mode

**Comment by KarolBedkowski** [comment]
Ok, I notice this problem with qt applications.
I hope this patch solve this problem: https://github.com/KarolBedkowski/kupfer/tree/fix-124-launching-app
