### ISSUE TITLE
Don't use deprecated xml2po (gnome-doc-utils)

### ISSUE THREAD

**Issue by City-busz** [kupferlauncher/kupfer#128]
Kupfer currently uses xml2po to generate localized help files. xml2po is part of the [gnome-doc-utils project](https://gitlab.gnome.org/Archive/gnome-doc-utils), which is deprecated and replaced by [itstool](http://itstool.org/) / [yelp-tools](https://gitlab.gnome.org/GNOME/yelp-tools).

Please replace the xml2po usage with itstool.

**Comment by KarolBedkowski** [comment]
Thanks.
