### ISSUE TITLE
Segmentation fault: Warning: invalid unclassed pointer in cast to 'WnckClassGroup'   self.base = None

### ISSUE THREAD

**Issue by everdred** [kupferlauncher/kupfer#130]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v319-20-ge51bdba2
Window Manager: Xfwm
Desktop Environment: Xfce
Linux Distribution: Debian Testing

Kupfer has regularly been crashing for me during normal usage; when typing to match an item the window disappears. (It is not always when matching the same item.)

When run with --debug, Kupfer crashes like so:

```
/usr/share/kupfer/kupfer/ui/browser.py:212: Warning: invalid unclassed pointer in cast to 'WnckClassGroup'
  self.base = None
Segmentation fault
```

The line preceding this seems like it's always a variation of:

`D [kupfer.core.data]: ranked in 0.021300 s`

**Comment by thorko** [comment]
I've the same issue here. Using KDE Plasma on Arch

**Comment by KarolBedkowski** [comment]
Not sure, but this may be related to  libwnck update. It's hard to debug - in my env it crash very rarely and I don't see any pattern.
Disable "Window  List" plugin should help for now.

**Comment by everdred** [comment]
@KarolBedkowski  Thank you. I can confirm that libwnck was recently update on my system, from 3.32.0-1 -> 3.36.0-1.

**Comment by KarolBedkowski** [comment]
Experimental patch for this problems: https://github.com/KarolBedkowski/kupfer/tree/bug130-wnck

**Comment by thorko** [comment]
This fix works. 
Is it possible to have it merged to kupferlauncher?
Thanks for the fix

**Comment by bluss** [comment]
Thanks Karol. I'm somewhat restricted in my ability to do releases right now, my Linux install has broken down. Can we work together to make a new official release?

The intention is to make a release with this PR's fix and the currently merged changes. Please don't rush in extra features, but potentially bug fixes :)

I can first write the version history, you make and check the dist tarball,  I can update git and the website?

**Comment by KarolBedkowski** [comment]
Hi,
Patch merged.

@bluss 
New release sound good. I can't promise I find enough time in this/next week, but I'll try to help.
I don't have any extra features waiting for merge. Also I don't see other patches ready (but I'll check open pr/issues). So master branch is ready for next release, I think.

**Comment by everdred** [comment]
I'm late, but this fixed it for me as well. Thank you.
