### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by elyoas** [kupferlauncher/kupfer#132]
No new releases have been made for the past 3 years. The master branch contains a lot of fixes that is not included in different distribution repositories.. I have personally moved away to gnome-do due to a problem in VLC launching, but I just noticed this was recently fixed. So I think kupfer is losing users..

**Comment by KarolBedkowski** [comment]
Work in progress: https://github.com/kupferlauncher/kupfer/tree/release-v320

@bluss  please take a look, seems to this version is ready for release. Thanks
