### ISSUE TITLE
plugin/websearch.py: OpenSearchSource fails trying to call Element.getchildren()

### ISSUE THREAD

**Issue by syslock** [kupferlauncher/kupfer#142]
Put OpenSearch XMLs in ~/.mozilla/firefox/profile/searchplugins/, e.g. https://de.wikipedia.org/w/opensearch_desc.php.
Start kupfer --debug
In Kupfer settings enable the extension "Search the Web" (websearch.py).

### Environment

Kupfer Version: 320-2
Window Manager: KDE/Plasma
Desktop Environment: KDE/Plasma
Linux Distribution: arch

### Actual Behaviour

Debug outoput on console:
```
Found following searchplugins directories
/home/<user>/.mozilla/firefox/<profile>/searchplugins
D [kupfer.plugin.websearch] OpenSearchSource: AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
...
D [kupfer.plugin.websearch] OpenSearchSource: Loaded 0 items
```
Search engines are unavailable in Kupfer.

### Expected Behaviour

```
Found following searchplugins directories
/home/<user>/.mozilla/firefox/<profile>/searchplugins
D [kupfer.plugin.websearch] OpenSearchSource: Loaded 9 items
```

Search engines are available in Kupfer.

### Suggested solution

In websearch.py, line 152, change:
```python
for ch in child.getchildren():
```
to:
```python
for ch in child:
```

**Comment by KarolBedkowski** [comment]
Thanks.
