### ISSUE TITLE
Access to thunderbird address book seems broken (TB 78.5.1, Kupfer 320 on Debian Bullseye)

### ISSUE THREAD

**Issue by ribosome08** [kupferlauncher/kupfer#144]
Access to the TB-adresses via Kupfer-Plugin used to work but no longer does (I guess since one of the latest Thunderbird-Updates). 

### Environment

Kupfer Version: 320 (not named in Bullseye, but I guess 320 is correct) 
Window Manager: Openbox 
Desktop Environment: pure Openbox or LXDE (makes no difference) 
Linux Distribution: Debian Bullseye

### Actual Behaviour

Adresses from TB do not show up when I enter search term. Also, in Kupfer, "Thunderbird --> Thunderbird Adress-Book" shows no entries other than "write new email". 

### Expected Behaviour

Adress-book entries should show up.

**Comment by KarolBedkowski** [comment]
Address book file format has changed from mab do sqlite.
Require add support for new file format...

**Comment by KarolBedkowski** [comment]
Solved in fa35ac90
Changes in address book may not be visible in Kupfer immediate. Close Thunderbird may be requred.
