### ISSUE TITLE
XFCE session management does not lock screen

### ISSUE THREAD

**Issue by Arborescent** [kupferlauncher/kupfer#146]
The lock screen functionality from the XFCE session management plugin does not work.

### Environment

Kupfer Version: 0+v320-1
Window Manager: Compton
Desktop Environment: XFCE
Linux Distribution: Ubuntu 21.04

### Actual Behaviour
Screen is not locked.

### Expected Behaviour
Screen is locked.

**Comment by Arborescent** [comment]
I was able to correct the problem by modifying `kupfer/plugin/session_xfce.py:15`
```diff
-- LOCKSCREEN_CMD = (["xdg-screensaver", "lock"], )
++ LOCKSCREEN_CMD = (["xflock4"], )
```
This invokes `xflock4` which is the command that locks your session in XFCE 4.

**Comment by KarolBedkowski** [comment]
Not sure, but look like bug in ubuntu's xdg-util version.  Debian last version work ok.
xdg-screensaver is more versatile than xflock4, so  I don't want change it for now.

**Comment by Arborescent** [comment]
Making the command configurable sounds like a satisfactory solution, thanks.
