### ISSUE TITLE
Version "undefined" in About

### ISSUE THREAD

**Issue by dfyockey** [kupferlauncher/kupfer#147]
### Environment

Kupfer Version: v320
Window Manager: Xfwm4
Desktop Environment: Xfce
Linux Distribution: Fedora 32

### Actual Behaviour
The word "undefined" is displayed in the "About Kupfer" dialog box where the Kupfer version should be.

### Expected Behaviour
Version information, such as "Version 320", should be displayed in place of "undefined".

**Comment by KarolBedkowski** [comment]
I don't see problem in Kupfer itself.
Build embed right version information in version_subst.py file.
If you are using  Kupfer from Fedora repository Fedora, bug my be in package.
If you are using development / source version - version is displayed as 'development version'.

**Comment by dfyockey** [comment]
Was using release file `kupfer-v320.tar.gz`, the first asset listed at https://github.com/kupferlauncher/kupfer/releases/tag/v320. Should have provided this info earlier; my mistake.

File `version_subst.py` in directory `build/kupfer/` reads:

    VERSION = "undefined"
    PACKAGE_NAME = "kupfer"
    LOCALEDIR = "/usr/local/share/locale"
    DATADIR = "/usr/local/share"

Downloaded each of the other release assets, configured and built, and examined `version_subst.py`. The results were identical to that above. Did the same with a download of the ZIP file from the Code page, with the same results.

Just a thought... The issue may be just a local thing due to the version of some build requirement that was installed from the Fedora repo and that differs from that used in development.

**Comment by KarolBedkowski** [comment]
Ok, I see problem.
Build from git version work ok.
In tar is missing "GIT_VERSION" file with exact version name.
This will be fixed in next release - i hope in next week.
Thanks for reporting.
