### ISSUE TITLE
mate-dictionary support missing

### ISSUE THREAD

**Issue by igorsantos07** [kupferlauncher/kupfer#148]
### Environment

Kupfer Version: 319
Window Manager: Compiz
Desktop Environment: Mate
Linux Distribution: Mint 20.1

### Actual Behaviour
The dictionary plugin doesn't show `mate-dictionary` as one of the options - it seems very very similar to `gnome-dictionary`, I guess they should work the same way?
I looked for a way to force it in `~/.config/kupfer/kupfer.cfg`, but the plugin doesn't show there either, even after changing its settings.

### Extras
Karol, thanks for closing the previous repository! :)
I ended up there looking for this exact issue and stumbled upon an ancient bug I had interacted with on Launchpad related to Mate support. I was wondering if there is any way to update/close things there as well? That may show on some Google searches, and it seems defunct if someone arrives there.

**Comment by KarolBedkowski** [comment]
#149 merged
