### ISSUE TITLE
Kuper launches Catfish search instead of folders

### ISSUE THREAD

**Issue by pmarlowe99** [kupferlauncher/kupfer#151]
When I use Kupfer to open folders like Home, Pictures, Documents, etc, it opens Catfish search. It should open the folders. This started happening on v. 319-5 for no reason today after working yesterday. It is still doing the same thing on v. 320-1, which I upgraded to today. Please see attached screen shots

I'm running Xubuntu 20.04. I've tried deleting the Kupfer cache, but no joy. 

![kupfer1](https://user-images.githubusercontent.com/49095627/116000114-86d90d00-a5b4-11eb-9ea4-8dff98ee854d.png)
![kupfer2](https://user-images.githubusercontent.com/49095627/116000116-89d3fd80-a5b4-11eb-9961-c7463ec90385.png)

!

**Comment by KarolBedkowski** [comment]
Please select in left panel any folder, in right panel "Set Default Application..." and in third panel select application what you want.

**Comment by pmarlowe99** [comment]
Thank you! Embarrassed I didn't think to check that. And how the default got changed.. that's a good question.
