### ISSUE TITLE
Bring back bash aliases and functions in commands plugin

### ISSUE THREAD

**Issue by zippy-zebu** [kupferlauncher/kupfer#152]
### Environment

Kupfer Version: 321
Window Manager: Unity/Compiz
Desktop Environment: Ubuntu Unity 21.04
Linux Distribution: Ubuntu

There used to be a [method](https://github.com/KarolBedkowski/kupfer-adds/blob/d7a65fa2db5bd1eb9f8e268808146ba0fcc764bc/kupfer/plugin/commands.py#L203) to get bash aliases and functions from .bashrc and .bash_aliases. It would be nice if we can have it here as well (with slight modification.)

The quick actions could be

1) Run in terminal -> here leaf.object is the exact command without quote;ex `ls -lcth`

2) Copy to clipboard (CTRL+C) -> So that it can be used anywhere including remote terminal.

Thanks.

**Comment by KarolBedkowski** [comment]
After some research - I don't see any reliable method to handle aliases and functions.

For aliases and functions (simplified) you need interactive shell.  But if you try run `bash -i` or `bash -l` from python - there are some quirks that can break everything. Bash try to do too much, execute some other programs etc - depending of user configuration. 
Of course - we can load some user defined files like .bash_aliases and use `expand_aliases`. Tricky, but work.
But still - there is not simple way to call in reliable way.  

As aliases are generally not recommended and should be replaced by functions or (better) by simple scripts - I don't see any value to add this. 

Close this ticket for now; PR will be welcomed for this.
