### ISSUE TITLE
Firefox Bookmarks plugin error, solved by adding uri=True to line 59 in firefox.py

### ISSUE THREAD

**Issue by smrtsmart** [kupferlauncher/kupfer#153]
### Environment

Kupfer Version: v321
Window Manager: xfwm4
Desktop Environment: XFCE
Linux Distribution: Fedora 34

### Actual Behaviour
The plugin is unable to read the firefox bookmarks. When I select "Firefox" -> "Firefox Bookmarks" under the default menu it says "Firefox Bookmarks is empty." kupfer --debug throws this message:
D [kupfer.plugin.firefox] BookmarksSource: Read bookmarks error: unable to open database file

### Expected Behaviour
The plugin should be able to import the bookmarks. Adding uri=True to line 59 in firefox.py and restarting kupfer solves the problem. The specific line is this:
with closing(sqlite3.connect(fpath, uri=True, timeout=1)) as conn:
The default python version on fedora 34 is 3.9.5 and maybe they changed the syntax requirements.

**Comment by KarolBedkowski** [comment]
Thanks.
I don't see this problem in Py 3.9.2 and FF 88.0.1 but definitively this param should be used.
