### ISSUE TITLE
Enhancement: Facilitate quitting Application processes if running

### ISSUE THREAD

**Issue by seltzered** [kupferlauncher/kupfer#159]
A use-case I've personally found useful when using Quicksilver is quickly quitting applications from the keyboard. 

Anecdotally it's been particularly useful to quickly quitting and restarting multi-document-interface apps that preserve state (e.g. code editors, web browsers). This could be implemented as a plugin around extending application actions  - filing this issue at the least as a note for myself. 

### Environment

Linux Distribution: Ubuntu 21.04

### Expected Behaviour
1. Open kupfer 
2. Search for application
3. If application is open, option to quit application is presented.

An option to possibly 'kill' the application could possibly be done as well but would argue it carries the risk of being too powerful of an action to be easily accessible.

**Comment by bluss** [comment]
If you have Wnck (optional dependency), then **there already is** an action called Close on a program.

It depends on something you might know from Mac OS that is not quite so simple in Linux: **matching program starters to windows to running applications**. There is no one way to do this correctly, and there are ways it can break. Kupfer could try harder (nobody is actively working on improving what's already there), but Kupfer certainly has tried to implement something like that.

**Comment by seltzered** [comment]
Thanks, realizing I'm using Kupfer on Wayland and Wnck support is X11-only. Will re-open when I figure out rough pathway for implementation.
