### ISSUE TITLE
Firefox plugins not functional

### ISSUE THREAD

**Issue by rcrx** [kupferlauncher/kupfer#160]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: 0+v319-5
Desktop Environment: cinnamon
Linux Distribution: mint

### Actual Behaviour

"Firefox keywords is empty"

### Expected Behaviour

For firefox keywords and bookmarks to be available.

**Comment by KarolBedkowski** [comment]
I don't see problem with this plugin, at last in last (v321) Kupfer version and 91 FF.
Be aware that keywords in FF is not the same as tags.
Search by bookmark tags is not supported in this moment.

**Comment by rcrx** [comment]
It doesn't detect either keywords or bookmarks with firefox 91.0.2 (64-bit).

**Comment by rcrx** [comment]
The issue was the version of kupfer packaged with mint and hosted in their repo. (v. 319 I think). Have to install additional dependencies to build 321 from tarball:
```
libc-dev-bin (2.31-0ubuntu9.2)
libc6-dev (2.31-0ubuntu9.2)
libcrypt-dev (1:4.4.10-10ubuntu4)
libexpat1-dev (2.2.9-1build1)
libpython3-dev (3.8.2-0ubuntu2)
libpython3.8-dev (3.8.10-0ubuntu1~20.04)
python3-dev (3.8.2-0ubuntu2)
python3-distutils (3.8.10-0ubuntu1~20.04)
python3-lib2to3 (3.8.10-0ubuntu1~20.04)
python3.8-dev (3.8.10-0ubuntu1~20.04)
zlib1g-dev (1:1.2.11.dfsg-2ubuntu1.2)
autoconf (2.69-11.1)
automake (1:1.16.1-4ubuntu6)
autotools-dev (20180224.1)
intltool (0.51.0-5ubuntu1)
```
