### ISSUE TITLE
Cannot set launch keys on Ubuntu 21.10 after Upgrade

### ISSUE THREAD

**Issue by kahironimashte** [kupferlauncher/kupfer#162]
### Environment

Kupfer Version: kupfer/impish,impish,now 0+v320-1 all [installed]
Window Manager: standard Ubuntu setting
Desktop Environment: gnome-shell-common/impish,impish,now 40.5-1ubuntu2 all [installed,automatic]
Linux Distribution: Ubuntu 21.10

### Actual Behaviour
I Upgraded to Ubuntu 21.10 from 20.04. Now I can not set the keys to launch Kupfer in Kupfer preferences. Its just greyed out. 
The behavior is correct if I run it with sudo, but this is no good option for daily use.

the console log says: [kupfer.ui.browser] WindowController: Trying to register <Ctrl>space to spawn kupfer.. failed

### Expected Behaviour
Before I could set a custom key to launch Kupfer. Now not even the default keys (ctrl+space) works.

**Comment by KarolBedkowski** [comment]
Please check is gir1.2-keybinder installed.

**Comment by kahironimashte** [comment]
The problem was that after the dist-upgrade the window manager changed. I switched back to the standard gnome option (gear on the login screen) and it worked again.
