### ISSUE TITLE
Segfaults under Wayland with new libwnck

### ISSUE THREAD

**Issue by toobaz** [kupferlauncher/kupfer#165]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: both 320 and git master ( 35759097a043e366968d8723ec77f5bcc47d0c99 )
Window Manager: Wayland
Desktop Environment: gnome-shell
Linux Distribution: Debian testing

### Actual Behaviour

When first called, Kupfer starts fine, but as soon as a key is pressed, it segtaults

### Expected Behaviour

Normal behavior.

This is due to the following regression in libwnck:
https://gitlab.gnome.org/GNOME/libwnck/-/issues/157

... but to be fair, it might be not too elegant to ask info on the current X session when no X session is running.

I'm sure cleaner approaches are possible, but the simplest fix I could find was to put the following lines:

```python3
import os
from gi.repository import Wnck
if 'WAYLAND_DISPLAY' in os.environ:
    Wnck.Screen.get_default = lambda *x : None
```

... before the ``if`` in ``kupfer.py`` (line 21). This restores the previous behavior of `get_default()`, and so kupfer works just fine.

**Comment by khurshid-alam** [comment]
libwnck is xorg only. Try running under xorg @toobaz

**Comment by toobaz** [comment]
> libwnck is xorg only. Try running under xorg @toobaz

Is kupfer xorg only?

I've been using it under Wayland for month... (and I'm still doing it, with the code added above).

**Comment by khurshid-alam** [comment]
Kufer depends on some libraries which are xorg only.

**Comment by toobaz** [comment]
Well, just for you to know, it should work again in Wayland if https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/52 is merged.

(Or if you make the minimal edit I am proposing, which won't harm anyway)

**Comment by KarolBedkowski** [comment]
In debian 11.6 (Gnome, wayland) i don't see problem with segfault. Wnck.Screen.get_display() return None and only report "is designed to work with x11 only..."
I found some places that result of get_display() is not checked and this may cause some problems.  
Also other things are totally broken - keybinder i.e.

**Comment by toobaz** [comment]
> In debian 11.6 (Gnome, wayland) i don't see problem with segfault

I can confirm: the bug emerged only when upgrading to testing (libwnck 43.0).

**Comment by toobaz** [comment]
@KarolBedkowski I can confirm your fix works fine (and looks better than mine). Do you plan to merge it in master?

(Just asking to understand if a patch on the Debian package is worth it)

**Comment by KarolBedkowski** [comment]
I will prepare new release - maybe tomorrow..
