### ISSUE TITLE
[Cinnamon] Super+space requires 2 space presses

### ISSUE THREAD

**Issue by igorsantos07** [kupferlauncher/kupfer#166]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v320 (shows "undefined" in the about popup; installed via apt)
Window Manager: marco?
Desktop Environment: Cinnamon 5.6.5
Linux Distribution: Mint 21.1

### Actual Behaviour
This is my first time on Cinnamon, so I'm kinda lost on what's going on - the default kupfer shortcut is Ctrl+Space, which works fine. However, if I change that to Super+Space, I actually have to use Super+Space+Space, in a quick succession, for kupfer to show up. No clue how to debug and my system doesn't seem to have another Super+Space as global shortcut.

### Expected Behaviour
Super+Space should just work, as configured, and as it used to work on Mate :upside_down_face:

**Comment by KarolBedkowski** [comment]
This is because of cinnamon menu shortcut. 
Right click on menu button (lm icon on taskbar) -> configure -> in section behavior "keyboard shortcut to open...", click on left "super l" and clear it with backspace.
Should resolve this problem.

**Comment by igorsantos07** [comment]
WOOOOOW. It's stealing half of the Kupfer shortcut??? That's nuts lol

Thank you and sorry for the trouble! Maybe that could be added to the shortcut settings screen, if the DE is identified as Cinnamon?
