### ISSUE TITLE
About shows version undefined and copyright only until 2017

### ISSUE THREAD

**Issue by revast** [kupferlauncher/kupfer#167]
### Environment

Kupfer Version: 3.22
Window Manager: xfce4
Desktop Environment: xfce4
Linux Distribution: ubuntu 22.04

### Actual Behaviour
About shows version undefined and copyright only until 2017
![image](https://user-images.githubusercontent.com/8189198/230415207-b12df883-01fe-42ad-8153-0c1906dbb468.png)

### Expected Behaviour
Should show proper version and date

**Comment by KarolBedkowski** [comment]
Missing versions is not Kupfer problem.
Version is read from source (if Kupfer is build from git source) or from GIT_VERSION that is created in build process and should be distributed in source dir.
2017 year will be corrected in next rev.
