### ISSUE TITLE
"Run in terminal" not sticking

### ISSUE THREAD

**Issue by everdred** [kupferlauncher/kupfer#170]
### Environment
Kupfer Version: 323-beta1-1
Window Manager: Kwin X11
Desktop Environment: KDE Plasma
Linux Distribution: Debian Sid

### Actual Behaviour
After locating a .sh script and launching it multiple times by selecting "Run in terminal" in the second pane, re-locating the script continues to show "Run" as the default action for the script. Even after using the menu option "Make Run In Terminal default for script.sh", "Run" continues to be the default action.

### Expected Behaviour
"Run In Terminal" should probably become the default action after a few launches, but definitely after using  "Make Run In Terminal default for script.sh".

**Comment by everdred** [comment]
Hi Karol, I understand how Kupfer should be working (I've enjoyed using it for many years, thank you for your work!) but since switching to the new beta version I'm seeing instances of organically-promoted actions being later forgotten, and explicitly-set default actions also being lost. 

I made a short screencast to demonstrate how setting "Make (...) Default" is not working as it used to. (I cleared Kupfer's app data before testing this with `rm -rf ~/.config/kupfer ~/.cache/kupfer`)

https://github.com/kupferlauncher/kupfer/assets/5367819/4c6e3ff3-e1ec-40a4-b093-9e2d603935cd

**Comment by KarolBedkowski** [comment]
ok, I will look at this.

**Comment by KarolBedkowski** [comment]
Problem should be solved in next branch.

**Comment by everdred** [comment]
And thank you for fixing this, Karol! It seems to be working for me now.
