### ISSUE TITLE
[fr] Make the `selected text` obj dynamic

### ISSUE THREAD

**Issue by proItheus** [kupferlauncher/kupfer#172]
### Actual Behaviour
I select `someword`, press <kbd>Control</kbd> + <kbd>G</kbd>, the `selected text` obj is selected, with value `someword`.

But when I select `anotherword`, press <kbd>Control</kbd> + <kbd>Space</kbd> to show kupfer, kupfer shows up, with `selected text` obj selected, but still with value `someword`.

And if I save `selected text` -> `some action` as a compound command, at the next time I execute it, `some action` will still receive `someword`, not current selected text.

### Expected Behaviour
> when I select `anotherword`, press <kbd>Control</kbd> + <kbd>Space</kbd> to show kupfer, kupfer shows up, with `selected text` obj selected

It's value should be `anotherword`.

> And if I save `selected text` -> `some action` as a compound command, at the next time I execute it, `some action` will still receive `someword`

`some action` should receive current selected text

### Background
I have an executable called `goldendict` , it's a dictionary program, and I can use `goldendict <word>` to look up <word> in it.

To query selected text in that program, I use `selected text` -> `pass to command` -> `goldendict`.

And because my using wayland, I can't assign a shortcut to `open kupfer with selected text`.

Alternatively, I think we can allow saving partially applied actions, that is, for actions needing indirect obj, save `action` -> `iobj1` as a `newaction` (maybe sth. similar to current compound command), and we can execute `obj`->`newaction` as a shorthand of `obj`->`action`->`iobj1`

**Comment by KarolBedkowski** [comment]
Hi,
Not sure if it resolve problem, but in current version you should be able to call any binding defined in Kupfer by something like:
`dbus-send --type=method_call --dest=se.kaizer.kupfer /interface se.kaizer.kupfer.Listener.RelayKeysFromDisplay string:"<Primary><Super>space" string:"" string:""`

Next release bring some updates that can help:

1. Fix for updating current leaf:  https://github.com/KarolBedkowski/kupfer/commit/83c01cbb6c34cf37851ec96ddf0198dbd1da432d

2. New dbus methods that can be used to show Kupfer with (i.e.) current selected text. https://github.com/KarolBedkowski/kupfer/commit/764243a89c144b2456c0ff2c4b636a508c6be7e7

3. There is also updated "dict" plugin that support Goldendict

In "next" version I can also create kfcom file (select "selected text" -> pass to command -> command -> ctrl+enter -> save as.. ). Executing this file is like executing sequence command. Not sure, it is work correctly in "current" version, though.
