### ISSUE TITLE
Kupfer change letter case when copy

### ISSUE THREAD

**Issue by a11g0rhythm** [kupferlauncher/kupfer#175]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v325
Window Manager: Plasma 5.27.10
Desktop Environment: KDE 
Linux Distribution: Nobara Linux 39

### Actual Behaviour

![1simplescreenrecorder-2024-02-18_10 49 35 mkv](https://github.com/kupferlauncher/kupfer/assets/1868730/f30edf7d-f163-4349-9137-44b20399d701)

### Expected Behaviour
Don't change letter case when copy

**Comment by KarolBedkowski** [comment]
Sorry, from this video and description I can't guess what is the problem. More information needed.

**Comment by a11g0rhythm** [comment]
Kufper change characters from upper case to lover case when you choose copy
