### ISSUE TITLE
Kupfer seems broken with Python 3.11.8 (but not 3.11.7)

### ISSUE THREAD

**Issue by torstenchr** [kupferlauncher/kupfer#176]
### Environment

Kupfer Version: 325
Window Manager: xfwm4
Desktop Environment: XFCE
Linux Distribution: Arch Linux

### Actual Behaviour

Running fully update Arch (as of 2024-04-09) with the latest Python (3.11.8) the program crashed with segmentation fault. The crash does not occur immediately but after some time when activating it through my selected shortcut keys.

Running with debugging on the terminal does not show any information as to why it crashed. The log only shows the output from processes started through kupfer.

Reverting back to previous version of python 3.11.7, this behaviour is not observed. 

I'm not sure if this a problem within kupfer itself or a bug in python.

### Expected Behaviour

Kupfer should run stable on version of Python > 3.0

**Comment by KarolBedkowski** [comment]
I don't see any problem with python 3.11.8 on Debian Sid.
What is last message before crash?
Try to disable all/some plugins.

**Comment by nanawel** [comment]
> Running fully update Arch (as of 2024-04-09) with the latest Python (3.11.8) the program crashed with segmentation fault. The crash does not occur immediately but after some time when activating it through my selected shortcut keys.

Same here. I can't find any hint using the console output or even `strace` :man_shrugging:

**Comment by KarolBedkowski** [comment]
I don't see any problem on fresh Arch installation (py 3.11.8, xfce4, Kupfer from repo or git and enabled all plugins).
Also other arch-based distro (EndeavourOS, manjaro) with py 3.11.8 work fine.
Without more derailed information I can't help

**Comment by torstenchr** [comment]
This is the dump I get from running in a terminal:

`
[torsten@rainier:/home/torsten]$ kupfer
Kupfer: A free software (GPLv3+) launcher
   Copyright © 2007–2023 Ulrik Sverdrup with others
   https://kupferlauncher.github.io/

INF [kupfer.core.sources] SourceController: Initial sources load
INF [kupfer.core.sources] PeriodicRescanner: scan Applications: 152 leaves in 0.00504 s
INF [kupfer.core.sources] PeriodicRescanner: scan torsten: 79 leaves in 0.00000 s
INF [kupfer.core.sources] PeriodicRescanner: scan Desktop: 10 leaves in 0.00000 s
INF [kupfer.ui.browser] WindowController: Trying to register <Super>space to spawn kupfer.. success
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py:1694: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  return _Gtk_main(*args, **kwargs)

(kupfer.py:4639): Gdk-CRITICAL **: 07:49:39.371: gdk_app_launch_context_set_screen: assertion 'screen == NULL || gdk_screen_get_display (screen) == context->display' failed
INF [kupfer.core.sources] PeriodicRescanner: scan torsten: 79 leaves in 0.00272 s
INF [kupfer.core.sources] PeriodicRescanner: scan Desktop: 10 leaves in 0.00078 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
INF [kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 1 s
INF [kupfer.core.sources] PeriodicRescanner: Campaign finished, pausing 60 s
Segmentation fault (core dumped)
`

**Comment by torstenchr** [comment]
I've attached a file where i had a run WITH debug info on as well.
[kupfer-debug.txt](https://github.com/kupferlauncher/kupfer/files/15006766/kupfer-debug.txt)

**Comment by torstenchr** [comment]
@KarolBedkowski  - i've been running with that line disabled for the entire weekend now and if does indeed seem to have fixed the issue! I haven't had any segmentation faults since!
