### ISSUE TITLE
Kupfer often crashes on first invocation

### ISSUE THREAD

**Issue by peterbjorgensen** [kupferlauncher/kupfer#179]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: 327
Window Manager: i3
Desktop Environment: None
Linux Distribution: Arch Linux

### Actual Behaviour
When I try to invoke kupfer with the hotkey the first time after a computer restart, it often crashes. When I launch kupfer again it seems to work. I launch kupfer initially with `exec kupfer` in my i3 config file.

### Expected Behaviour
No crashes

Are there any kupfer log files that might show the cause of the crash?

**Comment by KarolBedkowski** [comment]
Start kupfer with --debug argument; logs are printed on console.
