### ISSUE TITLE
AttributeError: 'gi.repository.Gdk' object has no attribute 'display_get_default'

### ISSUE THREAD

**Issue by dcelasun** [kupferlauncher/kupfer#22]
Hey,

I'm the maintainer of the kupfer [package](https://aur.archlinux.org/packages/kupfer/) on AUR. I've updated the package to v300, but when I start kupfer, I get the following error on the console. Kupfer itself is displayed and seems to work fine, but the stack trace says "please file a bug report", so here it is.

```
Error [kupfer.core.pluginload]: Loading multihead raised an exception:
Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer/core/pluginload.py", line 60, in exception_guard
    yield
  File "/usr/share/kupfer/kupfer/core/data.py", line 577, in _load_plugin
    plugin = pluginload.load_plugin(plugin_id)
  File "/usr/share/kupfer/kupfer/core/pluginload.py", line 31, in load_plugin
    initialize_plugin(item)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 374, in initialize_plugin
    initialize(plugin_name)
  File "/usr/share/kupfer/kupfer/plugin/multihead.py", line 23, in initialize_plugin
    display = gtk.gdk.display_get_default()
  File "/usr/lib/python3.6/site-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.6/site-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'display_get_default'
Error [kupfer.core.pluginload]: This error is probably a bug in multihead
Error [kupfer.core.pluginload]: Please file a bug report
Kupfer: A free software (GPLv3+) launcher
   Copyright © 2007–2017 Ulrik Sverdrup with others
   https://kupferlauncher.github.io/


```

**Comment by engla** [comment]
Ok, this is that not all plugins have been updated, so there are some bugs even in the ones left in the tree.

**Comment by engla** [comment]
Thanks for your work! I've updated the multihead plugin but I don't have the setup to test it out, so I have moved it to oldplugins/ anyway, so that it does cause unexpected bugs.

**Comment by dcelasun** [comment]
Hmm, did you push the commit? Or am I looking at the wrong place? :)

**Comment by engla** [comment]
I closed it before I had pushed it. But now it's threre. I ended up putting multihead in the bin (oldplugins) because I don't want it to cause serious bugs, it hasn't been tested. It's a new start for Kupfer, so plugins need to be redeveloped in a sense. I am not sure when multihead's use case even exists (Needs to use keybinder once per screen), I think common multidisplay setups don't need that.
