### ISSUE TITLE
Can't build in Ubuntu

### ISSUE THREAD

**Issue by hotice** [kupferlauncher/kupfer#25]
When trying to build Kupfer in Ubuntu, it checks /usr/bin/python, which is Python2 in Ubuntu. Maybe it should also check for /usr/bin/python3? Or maybe you know a way around this?

**Comment by engla** [comment]
The build needs to be configured, it won't find things automatically. Set `PYTHON`.

**Comment by engla** [comment]
I guess the configuration could be a bit smarter and try to find a Py 3 version.

**Comment by hotice** [comment]
Well I'm trying to build it in a Launchpad PPA which complicates things...

**Comment by engla** [comment]
How do you mean then? I'm sure the script can set an environment variable, if it can run commands?

**Comment by engla** [comment]
Ok, I've updated configure to look an extra time for Py 3. That should make it work by default on debian / ubuntu.

**Comment by engla** [comment]
Note that instead of `./waf` I'd run `python3 waf` and so on.

**Comment by hotice** [comment]
From what I could find, something like this is required to change the default Python version in Ubuntu: http://web.mit.edu/6.00/www/handouts/pybuntu.html Anyway, I'm giving up for now since it seems this is beyond my packaging skills.

**Comment by engla** [comment]
No, don't change the default! Only set `PYTHON=` explicitly when running waf.

**Comment by hotice** [comment]
I still get this:

```
Checking for program python              : python3 
python executable 'python3' different from sys.executable '/usr/bin/python'
```

**Comment by engla** [comment]
That's just a warning. Do report a bug if there is a problem.

**Comment by hotice** [comment]
Yeah, I was too quick to post that. Thanks!

**Comment by engla** [comment]
@hotice If you're making a public PPA, I'd be happy to link to it on the web page.

**Comment by hotice** [comment]
@engla it will be available sometime today. I'll let you know. I'm building packages for Ubuntu 17.04 (currently under development) and 16.10, even though it doesn't have the required GTK 3.22, but GTK 3.20 (the other deps are ok) because it works just fine for me. There is one issue with some GTK themes - it works with the default GNOME and Ubuntu themes but some third-party themes (like Adapta) cause Kupfer to display the text or icons out of place. But I assume that's due to the themes and not the GTK version.

Unfortunately Ubuntu 16.04 LTS (which has GTK 3.18) users are going to feel left out, but in my test in an Ubuntu 16.04 virtual machine, the Kupfer main window is blank so I guess it doesn't work properly at all with GTK 3.18.

**Comment by hotice** [comment]
@engla here's the PPA: https://launchpad.net/~webupd8team/+archive/ubuntu/kupfer 

I also posted an article about it on my website: http://www.webupd8.org/2017/02/kupfer-quick-launcher-ported-to-python.html

**Comment by engla** [comment]
Great! Thanks for the detailed story. Gtk 3 seems solid, but this is my first development experience with it so I haven't experienced the variability between versions (but I have heard of it). That's very worrying. The requirements in the README are like it says the version where I've tested it and know it to work, don't know the minimum deps.

**Comment by bluss** [comment]
please report any other theming issues. Especially if the themes are easier to install than adapta :wink:

**Comment by hotice** [comment]
But that's such a beautiful theme :) And it has packages for Arch, Ubuntu, etc. The other theme I encountered issues with was Numix, but it doesn't occur any more.

There is a minor issue that wasn't present in the first v3 releases, that occurs with any theme: the typed text is displayed on top of the border, maybe you can fix it? Screenshot: http://i.imgur.com/7CzdNhp.png (it's still at v307; I'll update to the latest version later today).

**Comment by bluss** [comment]
By the way the text padding issue should be fixed a few releases back, I have at least tried and it seemed to work.

@hotice Anyway, what name/nick/info should I use to thank you in credits for maintaining a PPA?

**Comment by hotice** [comment]
'Andrew from WebUpd8' is how people know me of, so something like that would be nice. Thanks!
