### ISSUE TITLE
Port AppIndicator code to pygi

### ISSUE THREAD

**Issue by hotice** [kupferlauncher/kupfer#26]
The Kupfer AppIndicator/tray is not working in Ubuntu (with Unity). Tested in Ubuntu 16.10 and 17.04 with Kupfer v303. The Kupfer v208 AppIndicator does show up in Ubuntu 16.10 (I didn't test the old version in Ubuntu 17.04).

Unfortunately there doesn't seem to be anything in the indicate what is causing this:
```
D [kupfer.ui.preferences] PreferencesWindowController: Standard Plugins: 40
D [kupfer.core.settings] SettingsController: Set Kupfer showstatusicon to False
[kupfer.core.sources] PeriodicRescanner: Starting new campaign, interval 3 s
D [kupfer.plugin.documents] RecentsSource: Loaded 606 items
D [kupfer.core.settings] SettingsController: Set Kupfer showstatusicon to True
D [kupfer.plugin.clipboard] ClipboardSource: Loaded 10 items
D [kupfer.plugin.notes] NotesSource: Loaded 0 items
```

**Comment by engla** [comment]
Yes, it is not yet ported. Source FIXME 

https://github.com/kupferlauncher/kupfer/blob/master/kupfer/ui/browser.py#L2014

The code is ported, the harder part unknown is how to know if AppIndicator or Status Icon should be used. The latter is actually deprecated, so we might switch to just app indicator.

**Comment by hotice** [comment]
Ok, thank you!

**Comment by bluss** [comment]
Plan of attack: Split the current status icon into two checkboxes. One for Gtk status icon and one for appindicator. So both or neither can be enabled at the same time. Needs attention from a developer using ubuntu.
