### ISSUE TITLE
(Python-3) Port GTG Plugin

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#32]
On Ubuntu (16.xx, 17.xx) and on Debian strech, stable version of GTG is **3.1** which work wonderfully well with old kupfer plugin. It's nothing more than a dbus-implementation of gtg. It should also work with python-3.

Thanks.

**Comment by bluss** [comment]
The plugin looks unproblematic. I can't port it, since I don't use GTG (It needs to be known to work before incorporating). Do you want to just try the gtg.py file in oldplugins and see if every item works? You can install it into `~/.local/share/kupfer/plugins/` and restart Kupfer. Preferably running `kupfer --debug` then and relaying any exceptions if there are. Thanks.

**Comment by khurshid-alam** [comment]
Thanks. I will do that. And yes it should work. May be some indentation fix is needed

(Btw Gtg is the same past couple of years with minor bug fixes. )

**Comment by bluss** [comment]
I've installed gtg, and there looks like at least one action (Mark as done) has an error. I'm not familiar enough with the app, so I can't really guide the plugin out of this. Does it still have relevant actions, or do they need to change? etc.

**Comment by khurshid-alam** [comment]
Yes, Mark-as-done doesn't work even for v208 (dbus interface error). It can find all the tasks with the new version and open it alright. 

`interface.Delete` using dbus method which has been deprecated. For dismissed and other action we have to use `ModifyTask` method. Kupfer already implemented as 
`_change_task_status(task_id, status)`

![gtg-dbus]()

For new stable api, I think these are the right status to pass. (I will recheck and let you know)

Dimissed: Postponed
Mark-as-done: Closed

**Comment by bluss** [comment]
I'd like to just drop support for the old API that the plugin seems to support. (Such choices are easy when you have a 5 year hiatus.. come back and scrap the old stuff!)

**Comment by khurshid-alam** [comment]
You mean gtg api <1? Yes those can be safely dropped.

**Comment by bluss** [comment]
api 1 too. The plugin itself calls the old one with "get_task" apiver 1. Not sure what the actual version is.

**Comment by khurshid-alam** [comment]
Found the error. This is the patch. Now Dismissed & Mark-as-done will work

```diff
def _change_task_status(task_id, status):
	interface, apiver = _create_dbus_connection(True)
-       task = interface.get_task(task_id)
+       task = interface.GetTask(task_id)
	task['status'] = status
```

**Comment by bluss** [comment]
Thanks for working with me. Your input is useful, but I'm working with a much bigger patch myself. I'll push & show :smile:

**Comment by bluss** [comment]
There's a lot more that can be done here. It's fun when you feel like it can be well integrated. Kupfer's gtg plugin should learn an action to do the full text search (like it can for Gnote), and should show tags.

**Comment by bluss** [comment]
Oh and the first thing on the diary would probably be a better default order of tasks.

**Comment by bluss** [comment]
see master

**Comment by khurshid-alam** [comment]
Thanks. I will check. :)

**Comment by bluss** [comment]
What's the thing about delete being deprecated? Should the action delete be deleted?

**Comment by bluss** [comment]
Released, but there are ample opportunities for polishing the plugin. I'd welcome contributions there.

**Comment by khurshid-alam** [comment]
No, Delete is working fine. 

Thanks for porting this.
