### ISSUE TITLE
Port RhythmBox plugin

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#33]
Nice to see some activity after after long. Please port Rhythmbox plugin.

Thanks.

**Comment by bluss** [comment]
Related to mpris support. I would prefer to see a more general way here. Although mpris may not cover library support for Rhythmbox.

**Comment by khurshid-alam** [comment]
@bluss 

Python2 implementation of the mpris plugin can be found here: https://github.com/hugosenari/Kupfer-Plugins/tree/master/mpris_2 by @hugosenari. 

I also commented on the issue asking the author if he wants to port his mpris plugin (https://github.com/hugosenari/Kupfer-Plugins/issues/2)

**Comment by bluss** [comment]
Ah it looks close to what I'd envision too (and have actually prototyped something simple like that)

Source: Players: Lists each active mpris player, with Play, Pause next, prev etc

hugosenari's idea of setting the last used one is valuable. I had an idea of an explicit action to lift any active one to be the primary one.

Rhythmbox doesn't support sending the library over mpris' dbus api, and neither does audacious, so it looks like it needs custom code for each player to get the library

**Comment by bluss** [comment]
See #34

**Comment by hugosenari** [comment]
Thank @khurshid-alam.
No change was required to run mpris_2.py.
Only mpris_2_plus.py don't work anymore. I will take a look some day.
And is good to see that now we also have an option with less external dependency, good work @bluss.

**Comment by bluss** [comment]
Hi @hugosenari you've created a very interesting project with the kupfer plugin marketplace. It's a great idea, it really needs something like that.

**Comment by bluss** [comment]
Library and play/queue support is back in the plugin, but I'm not 100% happy with the interaction with the queue. the details are up for discussion. (Like: When playing a single song, should it clear the queue or not?)
