### ISSUE TITLE
[Question] Is Pidgin going to be supported?

### ISSUE THREAD

**Issue by TamasBarta** [kupferlauncher/kupfer#40]
I was using Kupfer for its speed and its Pidgin support. I'm curious if it's going to be supported, or do you accept PRs, or it's unsupported purposefully.
Thanks!

**Comment by SanskritFritz** [comment]
Szia!
Plans are to port all plugins to python3. It just takes some time. If you were able to test or even send patches, that would be awesome.

**Comment by bluss** [comment]
I'm sorry, that's not the plan.

https://github.com/kupferlauncher/kupfer/blob/master/Documentation/VersionHistory.rst#kupfer-v300

> Many plugins are obsolete and have been dropped. Some old plugins can be updated, but I in general Kupfer wants to explore new kinds of interaction, and not necessarily collect all possible plugins in-tree

**Comment by bluss** [comment]
That said, the ones working on kupfer have a say in what plugins are incorporated. And we listen to feedback (Locate was revived after @SanskritFritz mentioned it).

**Comment by bluss** [comment]
I've put Pidgin back in. If you test it in current master, I'll put out a release with it after that.

**Comment by bluss** [comment]
It needed next to no porting. The new simplified plugin info display required it to not break the __author__ over two lines if it was the last info item, so that's the only thing that was fixed. I've also disabled contacts merging by full name, which I think was the most problematic part of contacts merging.

**Comment by bluss** [comment]
Fixed in 307
