### ISSUE TITLE
v306 no longer builds in Ubuntu 16.10, requires newer dependency to build documentation

### ISSUE THREAD

**Issue by hotice** [kupferlauncher/kupfer#41]
The latest Kupfer v306 requires a newer dependency to build documentation, so I can't build it in my Kupfer PPA any more (one solution would be to skip building documentation, or patch Kupfer, but I'd prefer not to do that). This is what I get when building Kupfer v306 in a Launchpad PPA for Ubuntu 16.10:
```
make[2]: Entering directory '/<<BUILDDIR>>/kupfer-0+v306/Documentation'
rst2html5 Contributing.rst > Contributing.html
/bin/sh: 1: rst2html5: not found
Makefile:9: recipe for target 'Contributing.html' failed
make[2]: *** [Contributing.html] Error 127
```
A complete log can be found here: https://launchpadlibrarian.net/306362742/buildlog_ubuntu-yakkety-amd64.kupfer_0+v306-1~webupd8~yakkety0_BUILDING.txt.gz

Looking at the log, it seems ``python3-docutils`` from Ubuntu 16.10 doesn't provide ``rst2html5``, but only ``rst2html``:
```
Setting up python3-docutils (0.12+dfsg-1) ...
update-alternatives: using /usr/share/docutils/scripts/python3/rst-buildhtml to provide /usr/bin/rst-buildhtml (rst-buildhtml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2html to provide /usr/bin/rst2html (rst2html) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2latex to provide /usr/bin/rst2latex (rst2latex) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2man to provide /usr/bin/rst2man (rst2man) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2odt to provide /usr/bin/rst2odt (rst2odt) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2odt_prepstyles to provide /usr/bin/rst2odt_prepstyles (rst2odt_prepstyles) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2pseudoxml to provide /usr/bin/rst2pseudoxml (rst2pseudoxml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2s5 to provide /usr/bin/rst2s5 (rst2s5) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2xetex to provide /usr/bin/rst2xetex (rst2xetex) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rst2xml to provide /usr/bin/rst2xml (rst2xml) in auto mode
update-alternatives: using /usr/share/docutils/scripts/python3/rstpep2html to provide /usr/bin/rstpep2html (rstpep2html) in auto mode
```

``python3-docutils`` is installed so I guess Kupfer now needs a version newer than the one available in Ubuntu 16.10 (0.12). Can this be changed back to rst2html? If not, I'll patch the PPA package to use  ``rst2html``.

**Comment by bluss** [comment]
It could be changed back. That makefile is for building the website, running it is something you and/or the debian maintainers have added to the build.

**Comment by hotice** [comment]
I can add it as a patch, no problem. Indeed, the Debian packaging (the official packaging as well as mine) installs all the documentation (from the Documentation folder) with the package. 

Well I guess I'll just close this no matter what you decide, it's not that important anyway, and it's just a small patch, nothing huge to maintain :)

**Comment by bluss** [comment]
This is the danger of “coming back”, I'm not oriented in which tools are now established and which ones are new. rst2html5 upgraded the default css of the pages by about two decades :wink:

**Comment by bluss** [comment]
By the way, thanks for the awesome support & feedback I get on the kupfer releases.
