### ISSUE TITLE
Remove Attach action in defaultmail

### ISSUE THREAD

**Issue by bluss** [kupferlauncher/kupfer#42]
It's attempting to use a `mailto:` link with `?attach=<file path>` which Thunderbird doesn't support. Does anything support this? Otherwise we should remove this action.

@SanskritFritz, what do you think?

**Comment by SanskritFritz** [comment]
I don't know the internals of this, and I personally don't use mailto: links in Kupfer. But I think we could safely treat Thunderbird as some kind of reference application, so if it doesn't support that notion, you could surely remove that option. 😄
