### ISSUE TITLE
[Feature request] inline editing of a textleaf inside kupfer

### ISSUE THREAD

**Issue by hetdegon** [kupferlauncher/kupfer#46]
Glad to see development has resumed! I use kupfer every day and it's great to see it'll continue working for years to come.

There's a little feature I'd love to see available, though, which is the ability to edit lines of text inside Kupfer itself (say to fix a typo, change an argument, or slightly modify a clipboard line or the "selected text" content). Would this be possible?
I used to do a gross hack to achieve this (by using a plugin to activate a `qdbus se.kaizer.kupfer /interface PutText "$1" &` command), but it'd be great to have that functionality built-in.

**Comment by bluss** [comment]
The Text → Show Text now shows the text in an editable window, so it's almost there. You can use the copy button to get it back, but we can add another button to send the text directly back to kupfer from the window.

Now I didn't want to start an avalanche of text editing features in the Show Text window, so maybe a separate action to edit in text editor is still wanted.

**Comment by hetdegon** [comment]
Something simple like selecting a textleaf and putting it back into the editing field natively (the text input you normally activate with ".", perhaps invoked the same way?) would suffice, no need for anything fancy. 
Funnily enough, I had already implemented something like this for 2xx, although it's not as convenient as what I am proposing. I ended up never using this implementation because of the extra steps involved.
(image included for comparison)
![snapshot21](https://cloud.githubusercontent.com/assets/323651/23074514/39bc8bee-f539-11e6-9999-d25f368e9465.png)

**Comment by bluss** [comment]
Ctrl + C, Ctrl + V does do what you are asking for if you have a text leaf in focus.

**Comment by hetdegon** [comment]
Hmm, I'd prefer to not wipe out the current clipboard content, but it does indeed work!. Since I use a beefy clipboard manager I guess I can live with it. Feel free to close this unless you want to reconsider a direct way, then!

**Comment by bluss** [comment]
The “force” text mode accelerator (default Ctrl + .) shows the currently inserted text, so it's hard to change that one. Say you typed sel to find the Selected Text object, then Ctrl + . will leave “sel” in the input entry, which seems to be desired. Not 100% sure, but this would be the place to change I think.

Another approach is to do

1. `zenity --text-info --editable` → Add to Favourites
2. TextLeaf → Filter through command → that command

**Comment by bluss** [comment]
Ah of course that needs a patch that I'm writing, for filter to command to properly use the current environment so that it can open a window. sec..

**Comment by bluss** [comment]
Ah, the last way is  TextLeaf → Write to Command → `kupfer`. Again, add `kupfer` as a command to favourites to have it stick around. Since Write to Command is fixed in master (soon in next release) this is more or less fixed with all the ways to do it (especially via the clipboard as well as writing text to kupfer).

So what I should realized before is that piping text to kupfer is the same as your custom dbus + PutText command.

**Comment by hetdegon** [comment]
Ooh, interesting, I totally didn't know that. 
Yeah between that, filter to and copypaste I think this is pretty much solved. Thank you very much!
