### ISSUE TITLE
Pressing down on a manually-selected catalog won't display the item list

### ISSUE THREAD

**Issue by hetdegon** [kupferlauncher/kupfer#47]
This one is a bit hard to explain, so I'll list the steps to reproduce this issue, instead:
1. Open Kupfer's main view (no text selected, default "blank slate" view)
2. Press the down key to list available catalogs
3. Press right to select the topmost "Applications" catalog
4. Press down to navigate the catalog. The list of entries won't show unless I press tab once (or twice, depending on the actions) to focus on it again.

I think that in this case the list should open when pressing down. This seems to be a legacy issue that I can reproduce in both 2xx and 308.1.

**Comment by bluss** [comment]
Thanks for the report. I can't reproduce, so maybe it has to do with something more specific? Which WM is this and does it use focus follows mouse or not?

When I try to reproduce:

1. Open main view, press Ctrl + R to reset state
2. Press down arrow once

That is enough to select the first item in the catalog and show the result list (which shows the following 9 items as well)

**Comment by SanskritFritz** [comment]
I can confirm this problem and also must add, it existed in pre 300 versions of Kupfer as well. It bugged me for long time but I got so used to it, that I forgot to report it.
It happens here on KDE5 Plasma but only if compositing (desktop effects) is turned on. When compositing is off, Kupfer behaves normally. Also using Openbox, Kupfer works as expected (even with compositing via compton).

**Comment by SanskritFritz** [comment]
I used SimpleScreenRecorder to show a demo:
https://youtu.be/j_exo8sm1dc

**Comment by bluss** [comment]
It is some kind of WM bug.

Under kwin in this situation, GTK reports the window to be visible, in the expected position and with the correct size. Kupfer is telling it to hide the result list window repeatedly during the same event, and in the end to show it again. The "visible" property logic is working, but the window manager doesn't like it.

I can put in a workaround for this, even though that's ugly. It makes the complicated gui code even harder to navigate. Since reshowing the window in an immediate but later event is less smooth than the experience with other window managers, I want to use the workaround for KWin only. Is this what you are using @hetdegon?

**Comment by hetdegon** [comment]
Yes, @bluss, I am using KDE5/Kwin as well! Odd it only happens with it.

**Comment by bluss** [comment]
Workaround is live. We're doing quick releases and may choose to revert fixes like this if they don't work out.

**Comment by hetdegon** [comment]
Seems to work perfectly. Thank you!

**Comment by bluss** [comment]
Great to hear. So on the topic of KDE, is there anything glaring missing for KDE integration in Kupfer? it's not really the way we are facing.

**Comment by SanskritFritz** [comment]
I also can confirm, the fix is working. Thank you.

**Comment by bluss** [comment]
On the topic of the result list, there's a configuration file only setting for the pixel height of the list of results: `list_height` as can be seen in `/usr/share/kupfer/defaults.cfg`. I'm using higher dpi, thus all the different size configs.

**Comment by hetdegon** [comment]
@Bluss other than this issue, the system tray icon doesn't show a menu with mouse click, but I never use it myself so it's a minor issue. Should I file it separately?

**Comment by bluss** [comment]
Yes if you want. The design is that single click on it shows/hides kupfer and right click shows the menu. It's a Gtk.StatusIcon and Gnome doesn't use that anymore, works fine in XFCE. Does it have a menu with right click for you? If not, a bug is welcome.

I don't use it either, don't need a status icon for an app that is always on.

**Comment by SanskritFritz** [comment]
> the system tray icon doesn't show a menu with mouse click, but I never use it myself so it's a minor issue.

That is definitely a KDE bug, many GTK applications have nonclickable icons in the KDE panel tray. xpad is one example, but non GTK x11vnc is another good example.

**Comment by hetdegon** [comment]
No menu, indeed. But only on 3xx. Since most of Kupfer can be controlled directly, it's barely an issue, though. I guess it can be left as-is until there's more demand for a fix.

**Comment by bluss** [comment]
sgtm. AppIndicator, equivalent of the Gtk.StatusIcon (Unity/Ubuntu only, not sure?) is still to be ported.

**Comment by bluss** [comment]
To be honest, the difference in behaviour in left and right click is part of the insanity. nm-applet (network manager) is another one that does it. Kupfer should change to have same behaviour (menu) on both, IMO.
