### ISSUE TITLE
While openning a note, Kupfer should not throw libnotify notification when Gnote is not running

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#50]
### Actual Behaviour
While trying to open a note using kupfer:
When the app is not running, dbus-interface is unavailable and it shows an error **notification**. Running it second time opens the note (as interface becomes available by then)

### Expected Behaviour
Instead it should try to open the note and should not throw libnotify notification. Or may be show a different notification like "Openning note...."

### Environment
Kupfer Version: git+master
Window Manager: Compiz/Unity
Desktop Environment: Unity-7
Linux Distribution: Ubuntu 17.04

**Comment by bluss** [comment]
Thanks. I noticed something like this but it seemed like a gnote bug to me, most other apps work fine with the same kind of activation + method call.

**Comment by bluss** [comment]
Oh apparently I destroyed the GTG task sort order when trying to write it in some kind of cute style (Active tasks should be first). So that will be fixed for the next version of kupfer.

**Comment by bluss** [comment]
I've spend unreasonably long time on this. Tomboy can have the same issue. I'm still surprised, direct activation + method call works fine with kzrnote, gtg, and many other programs we interact with.

**Comment by khurshid-alam** [comment]
In our case Kupfer proceeds as soon as it gets the required BusName but it requires few extra second before it can gnote content through dbus.

Beside Gnote isn't a proper d-bus activated systemd service. If you look at /usr/share/dbus-1/org.gnome.Gnote.service, it uses /usr/bin/gnote --shell-search. Usually these systemd services has something like 

```
[Service]
BusName=org.freedesktop.$servicename
```
BusName directive tells systemd to wait until the given bus name to appear on the bus before proceeding. But Gnote doesn't do this.

Running  /usr/bin/gnote --shell-search as an startup solves the problem. but Gnote should start as d-bus activated systemd service.

**Comment by bluss** [comment]
I've made a retrying fix for this. 

It does have this, is that not enough? Name=org.gnome.Gnote

**Comment by bluss** [comment]
Kupfer does get a proxy object /org/gnome/Gnote, it just doesn't register the interface and/or methods in time. GTG or kzrnote don't have this problem. That's what puzzles me.

**Comment by simonbcn** [comment]
Same problem here on Arch Linux with last version.

**Comment by bluss** [comment]
This should now be fixed in master, with the workaround route.

**Comment by bluss** [comment]
Oh I forgot to say, thank you Python for being completely bonkers, so that we can just make a proxy object that retries methods automatically.

**Comment by simonbcn** [comment]
Thanks, it works. :+1: 
@bluss I think that you should reported this in Python bugtracker.
