### ISSUE TITLE
Revive Empathy Plugin

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#53]
In my test everything works. Only some minor indentation fix required.

### Patch
```diff
--- a/oldplugins/empathy.py
+++ b/oldplugins/empathy.py
@@ -174,7 +174,7 @@
 
     def __init__(self, name=_('Empathy Contacts')):
         super(ContactsSource, self).__init__(name, "Contacts")
-        self._version = 2
+        self._version = 3
         self.unpickle_finish()
 
     def pickle_prepare(self):
@@ -216,25 +216,25 @@
                     self.output_info(ex)
                     contacts = None
                 if contacts:
-                        contacts = [c for c in contacts]
-                        contact_attributes = connection.Get(CONTACT_IFACE, "ContactAttributeInterfaces")
-                        contact_attributes = [str(a) for a in contact_attributes]
-                        contact_details = connection.GetContactAttributes(contacts, contact_attributes, False)
-                        for contact, details in contact_details.items():
-                                try:
-                                    status_code = details[_ATTRIBUTES.get("presence")][1]
-                                except KeyError as ex:
-                                    self.output_info('Presence could not be established with %s. Leaving unknown.' % ex)
-                                    status_code = 'unknown'
-                                if not show_offline and status_code == 'offline':
-                                    continue
-                                yield EmpathyContact(
-                                        details[_ATTRIBUTES.get("jid")],
-                                        details[_ATTRIBUTES.get("alias")],
-                                        _STATUSES.get(status_code),
-                                        '', # empathy does not provide resource here AFAIK
-                                        valid_account,
-                                        contact)
+                    contacts = [c for c in contacts]
+                    contact_attributes = connection.Get(CONTACT_IFACE, "ContactAttributeInterfaces")
+                    contact_attributes = [str(a) for a in contact_attributes]
+                    contact_details = connection.GetContactAttributes(contacts, contact_attributes, False)
+                    for contact, details in contact_details.items():
+                        try:
+                            status_code = details[_ATTRIBUTES.get("presence")][1]
+                        except KeyError as ex:
+                            self.output_info('Presence could not be established with %s. Leaving unknown.' % ex)
+                            status_code = 'unknown'
+                        if not show_offline and status_code == 'offline':
+                            continue
+                        yield EmpathyContact(
+                                details[_ATTRIBUTES.get("jid")],
+                                details[_ATTRIBUTES.get("alias")],
+                                _STATUSES.get(status_code),
+                                '', # empathy does not provide resource here AFAIK
+                                valid_account,
+                                contact)
 
     def get_icon_name(self):
         return 'empathy'
```

### Environment

Kupfer Version: git+master
Window Manager: Compiz
Desktop Environment: Unity
Linux Distribution: Ubuntu 17.04

**Comment by bluss** [comment]
Thanks! The help with testing makes the whole difference.

**Comment by bluss** [comment]
I'll reopen this, not certain we can add the plugin. Empathy itself is buggy, and open chat does not work from kupfer, and it does not work from inside Empathy itself. Whatever the cause is, it reflects poorly on kupfer too.

**Comment by khurshid-alam** [comment]
Yes I was about to open a new issue about this.

I am using Empathy 3.12, default version on Ubuntu 17.04. If I delete everything under `~/.cache/kupfer`, open chat works (I had to connect at-least one account in empathy before launching kupfer).

![empathy](https://cloud.githubusercontent.com/assets/1333217/23260340/588cc594-f9f7-11e6-899d-19c1f7104c93.gif)


### However after reboot I got error like this:

> ERROR:dbus.connection:Unable to set arguments (<ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0xb325d14c> :1.84 /org/freedesktop/Telepathy/Account/gabble/jabber/khurshid_2ealam_40jabber_2corg0 at 0xb0d0934c>, dbus.Dictionary({'org.freedesktop.Telepathy.Channel.TargetHandle': dbus.UInt32(5), 'org.freedesktop.Telepathy.Channel.ChannelType': dbus.String('org.freedesktop.Telepathy.Channel.Type.Text', variant_level=1), 'org.freedesktop.Telepathy.Channel.TargetHandleType': dbus.UInt32(1, variant_level=1)}, signature=None), dbus.Int64(1487850988), 'org.freedesktop.Telepathy.Client.Empathy') according to signature None: <class 'ValueError'>: invalid literal for int() with base 10: dbus.String('org.freedesktop.Telepathy.Channel.Type.Text', variant_level=1)
> Traceback (most recent call last):
>   File "/usr/share/kupfer/kupfer/ui/browser.py", line 1605, in _activate
>     self.data_controller.activate(ui_ctx=self._make_gui_ctx())
>   File "/usr/share/kupfer/kupfer/core/data.py", line 803, in activate
>     res, ret = ctx.run(leaf, action, sobject, ui_ctx=ui_ctx)
>   File "/usr/share/kupfer/kupfer/core/commandexec.py", line 303, in run
>     ret = activate_action(execution_token, obj, action, iobj)
>   File "/usr/share/kupfer/kupfer/core/commandexec.py", line 80, in activate_action
>     return _activate_action_single(obj, action, iobj, kwargs)
>   File "/usr/share/kupfer/kupfer/core/commandexec.py", line 88, in _activate_action_single
>     ret = action.activate(obj, **kwargs)
>   File "/usr/share/kupfer/kupfer/plugin/empathy.py", line 114, in activate
>     message_channel_path = channel_dispatcher_iface.EnsureChannel(account, channel_request_params, ticks, EMPATHY_CLIENT_IFACE)
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
>     return self._proxy_method(*args, **keywords)
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
>     message.append(signature=signature, *args)
> ValueError: invalid literal for int() with base 10: dbus.String('org.freedesktop.Telepathy.Channel.Type.Text', variant_level=1)

### Other Bugs

- [ ]  Empathy must start and connect before kupfer to view contacts. 

- [ ] When changing status to "offline" , instead of setting the presence offline, kupfer completely disabled the account. It can only be re-enabled from empathy-account-manager.

**Comment by bluss** [comment]
Have done some tweaks in git. For me, empathy does not work. The program itself does not allow chatting even when connected via jabber. So I can't do much more.

**Comment by khurshid-alam** [comment]
Alright. Closing.

**Comment by bluss** [comment]
Ok it's back in oldplugins. It can still be revived if everything works.

**Comment by khurshid-alam** [comment]
It's working for me. I only encounter the error only few times. The error happens probably when telepathy sends a empty string which can not be converted to int64. But since then I couldn't reproduce it. I will take a deeper look later.
