### ISSUE TITLE
Show with Selection doesn't work here

### ISSUE THREAD

**Issue by SanskritFritz** [kupferlauncher/kupfer#55]
Kupfer Version: 311 or older
Window Manager: kwin
Desktop Environment: KDE Plasma 5
Linux Distribution: archlinux
I have set Show with Selection shortcut, but kupfer simply appears as if the normal shorcut were pressed.
All I get in the terminal is this:
```
[kupfer.ui.browser] WindowController: Trying to register <Alt>F2 to spawn kupfer.. success
[kupfer.ui.session] SessionClient: Warning: Not able to connect to current desktop session, please Quit before logout to save kupfer's data.
```

**Comment by bluss** [comment]
Is the clipboard plugin enabled? It is what defines the selected text proxy object.

**Comment by bluss** [comment]
Session message is a separate missing feature. Need session manager support for more environments.

**Comment by SanskritFritz** [comment]
> Is the clipboard plugin enabled? It is what defines the selected text proxy object.

Ah ha! Enabling it fixed the problem. Sorry for the noise.
