### ISSUE TITLE
GTG: Add action accelerators

### ISSUE THREAD

**Issue by bluss** [kupferlauncher/kupfer#59]
Add default action accelerators that match the GTG shortcuts

cc @khurshid-alam Input welcome.

**Comment by khurshid-alam** [comment]
Yes, that would be awesome. 

### GTG Shortcuts

| Action       	| ShortCut 	|
|--------------	|----------	|
| New Task     	| Ctrl+N   	|
| Mark as Done 	| Ctrl+D   	|
| Dismiss      	| Ctrl+I   	|
| Delete       	| DEL      	|

**Comment by khurshid-alam** [comment]
Will this be something similar to trigger plugin? Although I don't really understand trigger actions. :/

**Comment by bluss** [comment]
Triggers are for global keyboard shortcuts

This is for https://github.com/kupferlauncher/kupfer/pull/58 it's going to be awesome. Though the proposal is to allow only a uniform scheme of <modifier> + letter

**Comment by bluss** [comment]
A good example for a trigger would be Selected Text → Create Task. It will work in any program as a global shortcut.

I'd like to focus on in-kupfer shortcuts for now because wayland and such technologies mean that our global keyboard shortcut system is incompatible. That's an open issue to solve.

**Comment by khurshid-alam** [comment]
T or N for default accelerator Create Task? We could also have similar thing for gnote (free-text --> Create Note).

And yes, in-kupfer shortcuts are preferable since it doesn't mess with other shortcuts across different desktop/shells.

**Comment by bluss** [comment]
I have added a create task action (Gtg app → Create Task), there is already *Text* → Create Task. The first one can use N as the accelerator, I'm reluctant to add anything by default to the one that applies to text. The user can set their own ones there.

So in the case of action accelerators they are only available if the current object has the action.

**Comment by bluss** [comment]
There is no feature that addresses a need for kupfer-global shortcuts if that is needed (something like triggers, but only when kupfer is in the front).
