### ISSUE TITLE
Notification upon successful disk unmount

### ISSUE THREAD

**Issue by ishouldbedany** [kupferlauncher/kupfer#64]
### Environment

Kupfer Version: git as of 3.03.20 (v314)
Window Manager: Mutter
Desktop Environment: GNOME 3.22 w/ GNOME Shell
Linux Distribution: Fedora 25

### Actual Behaviour
Using the "Volumes and Disks" plugins, whenever I unmount a volume, no feedback is provided.

### Expected Behaviour
After am unmount operation, a notification should be shown providing feedback (either positive or negative) about the operation and whether the disk can be safely removed. 

#### Extra
Thanks for bringing Kupfer back from the dead. I was a GNOME Do user and it was one of the most satisfying computing experiences of my life. Kupfer is bringing that back. So productive now!

**Comment by bluss** [comment]
I'm not sure I agree. Succeeding is the default, does it really need a notification?

**Comment by ishouldbedany** [comment]
GNOME, even in case of sucess, shows a notification. Maybe the rationale is that as an early removal may lead to data corruption, so that extra feedback is important.

**Comment by bluss** [comment]
That's a good point.

**Comment by ishouldbedany** [comment]
Great! Thank you.
