### ISSUE TITLE
Allow to use dark version of the GTK theme

### ISSUE THREAD

**Issue by ishouldbedany** [kupferlauncher/kupfer#66]
### Environment

Kupfer Version: git March 3 (v314)
Window Manager: Mutter
Desktop Environment: GNOME 3.22
Linux Distribution: Fedora 25

### Actual Behaviour
Kupfer uses the normal version of the current GTK theme.

### Expected Behaviour
An option in settings to activate the dark version of the current select theme. Dark themes make it look nicer and improve contrast with the mostly white webpages/app backgrounds and bright/colorful icon themes, which seem to be the norm these days. Attached is a screenshot of Kupfer using Adwaita-Dark, 
activated through GTK+ Inspector. 

![image](https://cloud.githubusercontent.com/assets/6266595/23547928/68381a16-0005-11e7-9878-dfeb9b1daa64.png)

Editing the launcher command to start in the dark theme using the environment variables is possible, but makes every program/window Kupfer spawns black as well.

**Comment by bluss** [comment]
Right, this makes sense.

Educate me, I'm new to Gtk 3. Does every theme have "the dark variant" of itself? How would it be selected?

**Comment by ishouldbedany** [comment]
I'm just a curious end user, but my understading is that you can bundle a dark variant of your theme and it will be used in applications that specifically request it (media-heavy applications, like GNOME Photos or Totem, do it). If an application requests a dark theme variant and the current theme does not have it, it falls back to the regular variant.

GNOME default theme, Elementary, and other popular community themes have dark variants.

**Comment by bluss** [comment]
Indeed, there seems to be no more mystery than this: https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/Settings.html#Gtk.Settings.props.gtk_application_prefer_dark_theme

I would prefer to load a kupfer-specific gtk 3 settings.ini for this. It would solve most of the issues of user theme customization.

**Comment by khurshid-alam** [comment]
Yes custom-theme-plugin is missing from new kupfer. In old kupfer user can choose light or dark version from preference. And I wouldn't want to depend on `gtk-application-prefer-dark-theme` as not every theme provide a proper dark-scheme (it theme doesn't have a dark-scheme, it will fall back to default dark-scheme which may not look good). 

Here is my suggestion:
1. Provide a dark-theme-mode in plugins/preference like before. It can be hardcoded.

2. In addition, Kupfer should also provide ability to theme it using css. It will overwrite the default (light or dark) theme.

@chaitanya-lakkundi opened a pull-request before (#49) regarding this. I think his last couple of commits (which doesn't change the layout) are exactly what we are looking for. He commented that he would create another PR only for css-capability without changing the layout or adding anything extra.

**Comment by bluss** [comment]
Since kupfer has already named its window and widgets, it should be possible to put specific css for it in the user's gtk.css file. Some theme support is needed if themes should be able to change position/orientation of some widgets or have a theme selector in preferences.

**Comment by bluss** [comment]
On the topic of theming, rounded corners of the window were lost in the migration to Gtk 3. It looks like the Apis for cairo regions is not properly exposed in gi, so there is no way to call shape_combine_region to have rounded corners.

**Comment by khurshid-alam** [comment]
@bluss 
>Since kupfer has already named its window and widgets, it should be possible to put specific css for it in the user's gtk.css file.

Are you referring to something like this?

```css

#kupfer {
    background: @theme_bg_color;
}

.matchview {
    border-radius: 25px;
}

#kupfer-preedit {
}

#kupfer-object-pane {
}

#kupfer-action-pane {
}

#kupfer-indirect-object-pane {
}

#kupfer-list {
}

#kupfer-list-view {
}

*:selected .matchview {
    font-size: 25px;
}
```

**Comment by bluss** [comment]
I know next to nothing about css theming, but yes, those are the widget names. It should be possible to scope the rules even tighter so they only apply to windows named `#kupfer` or so.

Start of doc is https://kupferlauncher.github.io/Documentation/GTKTheming.html

**Comment by bluss** [comment]
For example using `window#kupfer .matchview { border-radius: 45px; }`. I'm unsure myself how the nesting rules work.

**Comment by khurshid-alam** [comment]
Yes. It would work. I am testing if it is working as intended. 

Btw, is there any specific to set gtk requirement so high (3.22). If it is because og themming, we can theme it for both gtk-3.18 and >=gtk-3.22.

**Comment by chaitanya-lakkundi** [comment]
I have made a PR with partial support to dark theme (only using CSS).

**Comment by bluss** [comment]
The reason given in the README was honest: With a new port, I have never tried any Gtk version other than 3.22, and thus I don't know anything more than that 3.22 works.

I've tried 3.20 by now and it seems to work fine.

**Comment by bluss** [comment]
This is actually a very simple plugin, to just toggle the GtkSettings flag. It's much neater and easier to design the user interface by adding a plugin rather than remaing the preferences and connecting different parts of the app. I'm partial to this as a solution to this issue of “Prefer Dark Theme Variant” toggle.


```python

__kupfer_name__ = _("Prefer Dark Theme")
__description__ = ""
__version__ = "2017.1"
__author__ = ""

from gi.repository import Gtk

from kupfer import plugin_support, pretty

__kupfer_settings__ = plugin_support.PluginSettings(
    {
        "key" : "prefer_dark",
        "label": _("Prefer Dark Theme"),
        "type": bool,
        "value": True,
    },
)

def initialize_plugin(name):
    pretty.print_info(__name__, "Initialize", name)
    use_theme(__kupfer_settings__['prefer_dark'])
    __kupfer_settings__.connect_settings_changed_cb(on_change_theme)

def finalize_plugin(name):
    pretty.print_info(__name__, "finalize", name)
    use_theme(None)

def on_change_theme(sender, key, value):
    use_theme(value)

PREFER_DARK = "gtk-application-prefer-dark-theme"

def use_theme(enabled):
    pretty.print_info(__name__, "updating setting to", enabled)
    s = Gtk.Settings.get_default()
    if enabled is None:
        s.reset_property(PREFER_DARK)
    else:
        s.set_property(PREFER_DARK, enabled)
```

**Comment by chaitanya-lakkundi** [comment]
A very good and neat solution indeed !
Just another idea (related to the issue of changing layout ).

We can separate the view and controller by providing a separate XML file for the Layout (hbox and vbox etc. ) and then load that file using a function. In this way we can provide multiple layout functionality for the user.

A new layout would just mean creating a new xml file. We can extend the xml file to provide options to hide panes, change font size, alter height and width etc. 

Please suggest your opinions on this thought.

**Comment by bluss** [comment]
The simple toggle is in kupfer 319, it's a new plugin. Note that it can be used to prefer the GTK light theme if the global default is prefer dark, too.

Now for more specific kupfer themeing, that's a different thing.
