### ISSUE TITLE
Making small fixes in the docs?

### ISSUE THREAD

**Issue by SanskritFritz** [kupferlauncher/kupfer#69]
I found some errors in the documentation (specifically in PluginAPI.rst the plugin path should be share/kupfer/plugin). May I directly edit the document thus creating a new commit or do you prefer to fix it yourself either through a pull request or based on this report?

**Comment by bluss** [comment]
I think you can just go ahead and edit if it's docs. For code I think we should use PRs.

About this issue, I'm pretty sure it is `plugins` with an s. This is defined in kupfer/plugin/__init__.py

```python
    # Add plugins in data directories
    __path__.extend(config.get_data_dirs("plugins"))
```

**Comment by SanskritFritz** [comment]
How come I have ```/usr/share/kupfer/kupfer/plugin/``` in my kupfer installation?
```$HOME/.local/kupfer/plugins``` works however.

**Comment by bluss** [comment]
That's the install location for kupfer's python directory, not where user plugins go.

**Comment by bluss** [comment]
`/usr/share/kupfer/plugins` would be a system wide directory that can be used.

**Comment by SanskritFritz** [comment]
Oh, totally misunderstood the concept then, thanks.

**Comment by bluss** [comment]
No problem.
