### ISSUE TITLE
Kupfer crashes when closing Text window

### ISSUE THREAD

**Issue by SanskritFritz** [kupferlauncher/kupfer#71]
### Environment
Kupfer Version: 316
Window Manager: kwin
Desktop Environment: Plasma5
Linux Distribution: archlinux

"Show text" displays a window with the text. Closing the window causes Kupfer to crash.
```
(kupfer.py:8858): Gdk-ERROR **: The program 'kupfer.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 10875 error_code 3 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
fish: “kupfer” terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by bluss** [comment]
There are three ways to close, do all have the same result? (X button on Window, Close button in lower corner, Escape key).

**Comment by SanskritFritz** [comment]
Only pressing the Close button with the mouse (!) crashes Kupfer. Even pressing alt-c works ok. (BTW, both buttons have the c underlined, so alt-c only puts the keyboard focus to Copy).

**Comment by bluss** [comment]
They use their stock mnemonics, so I guess GTK likes it that way. Using a different language I have different results.

**Comment by bluss** [comment]
I'm confident this should fix it (It did not reproduce here though), because the existing code was entirely wrong, destroying a GdkWindow instead of a GtkWindow.

**Comment by SanskritFritz** [comment]
And you were right! Thanks.
