### ISSUE TITLE
Hotkey or triggers don't work if kupfer is started without stdout attached

### ISSUE THREAD

**Issue by SanskritFritz** [kupferlauncher/kupfer#72]
Kupfer Version: 316
Window Manager: kwin
Desktop Environment: plasma 5
Linux Distribution: archlinux
I have to start kupfer from a terminal, or via nohup, otherwise no global hotkeys are working. Kupfer shows up in the process list, but is unusable since the gui doesn't show up.

**Comment by bluss** [comment]
This is doubly workarounded so I think it's effectively fixed. `kupfer --no-splash` (autostart) does not read stdin, neither does it when DESKTOP_STARTUP_ID is set.

**Comment by SanskritFritz** [comment]
Indeed this way it is fixed. I can have Kupfer in my autostart! 😃

**Comment by marscher** [comment]
If one uses the option in the GUI to autostart Kupfer, it already adds the no splash option. However the GUI does not show up (also kde plasma) with the progress running in the background.

So I can not see why this issue has been closed.

**Comment by bluss** [comment]
@marscher Please open a new issue. We can't track bugs we don't know about. This one was closed because the reporter confirmed that their issue was fixed.

**Comment by SanskritFritz** [comment]
Indeed it is working here, I just tested using the option in Kupfer. What version of Kupfer are you using @marscher ?

**Comment by marscher** [comment]
Using version 318.

**Comment by marscher** [comment]
Sorry guys, i missed a dash in the option... (so indeed not worth opening another issue)
