### ISSUE TITLE
Kuper terribly confused in multi-monitor setup with different resolutions

### ISSUE THREAD

**Issue by jonhoo** [kupferlauncher/kupfer#74]
I have a dual-screen setup that seems to confused Kupfer to no end about where the launcher should appear, and what size it should be. In particular, I have two screens: one 1920x1080, and one 1200x1920. The second one is rotated, and placed to the right of the 1920x1080 screen, and is marked as my `Primary`.

As I'm told pictures are worth thousands of words, take a look at the different kupfer invocations I end up with depending on a) which screen my mouse is on, b) which screen has the active virtual desktop, c) whether kupfer has recently been restarted, and d) the phase of the moon.:

[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-1.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-1.png)
[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-2.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-2.png)
[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-3.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-3.png)
[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-4.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-4.png)
[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-5.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-5.png)
[![confused-kupfer](https://jon.tsp.io/share/kupfer-issue-74/confused-6.thumb.png)](https://jon.tsp.io/share/kupfer-issue-74/confused-6.png)

### Environment

Kupfer Version: v317
Window Manager: xmonad
Desktop Environment: None
Linux Distribution: Arch Linux

**Comment by bluss** [comment]
Thanks for the detailed report.

The design is that it should move to the monitor where the pointer is, so that part seems to be as intended. (Please open additional issue if this is an issue).

I don't really know what configuration is possible here. Do your different monitors have different dpi configured? at some level?  The same way, Gtk 3 allows you to set a scaling factor of 1 or 2, is that used on one and not the other (I don't know if that's possible).

Gtk introduced a lot of new monitor API in version Gtk 3.22. I don't think anything should have changed behaviour (we're not using the new apis I think) and it would be great to know which version you are using.

**Comment by jonhoo** [comment]
My experience has been that the launcher appears on the monitor that holds the currently active virtual desktop, not which screen the mouse cursor is on. But that's actually the behavior I expect. The weird part is that the location and size of the launcher seems to depend on which monitor the mouse is on (i.e., it shows differently if the mouse is on the same screen as the one the launcher appears on and if it's on the other one).

I'm on `gtk3 3.22.9+2+gaebe3a74ec-1`. I'm not using per-monitor DPI scaling as far as I'm aware. The left screen *is* a high-DPI screen, but I've manually set its resolution to 1920x1080 (which is half it's native resolution) instead of fiddling with DPI (I'm just using 96). Interestingly, `xdpyinfo` reports that I have *one* screen of size `3120x1920`, but I don't know if that's relevant.

**Comment by bluss** [comment]
Ok, as usual bugs are very hard to fix unless they can be reproduced on the developer end. Thanks for being so detailed though. Here's a total shot in the dark you could try, just removing some potentially wrong size allocation functions: remove-do-virtual branhch of this repo https://github.com/kupferlauncher/kupfer/tree/remove-do-virtual 

One can start Kupfer directly from the git repo without building anything, just using `./kupfer-run --debug`  should be fine.

**Comment by jonhoo** [comment]
Unfortunately that branch only seems to make things worse if anything. Now the window sometimes changes sizes even between invocations where the mouse doesn't move and the active virtual desktop doesn't change.

**Comment by bluss** [comment]
There's a new shot in the dark on that branch, something that's more reasonable to change anyway (change from inheritance to composition for Gtk Widgets).

**Comment by bluss** [comment]
The idea behind that is simply to get us out of the responsibility of widget sizing at all

**Comment by bluss** [comment]
@chaichaitanya-lakkundi I think I want to do the inheritance vs composition changes on the remove-do-virtual branch either way, even if the experiment to solve this doesn't work out (not just yet, branch is not ready). It should not be very disruptive.

**Comment by jonhoo** [comment]
Nope, still didn't change much :/

**Comment by bluss** [comment]
Allright, thanks for trying anyway! Any other Gtk 3 program that behaves like this?

If you don't tire, I'd try

```
KUPFER_WINDOW_TYPE_HINT=normal ./kupfer-run --debug
KUPFER_WINDOW_TYPE_HINT=splashscreen ./kupfer-run --debug
```

Yeah, it's pretty hopeless. Without access to a reproducing I'm in the dark here. I'll try to google around for something similar now.

**Comment by bluss** [comment]
Another unresolved bug I see is that I haven't figured out how to draw the highlight in the theme's selection color in a way that's portable across themes. Primary pane should have the rounded highlight when kupfer starts

**Comment by bluss** [comment]
(Updated the test branch with another step in the same vein).

**Comment by bluss** [comment]
You know what, this xmonad + gtk app bug sounds familiar https://github.com/xmonad/xmonad/issues/34

**Comment by bluss** [comment]
And this http://haskell.1045720.n5.nabble.com/Issue-414-in-xmonad-Wrong-floating-window-sizes-on-multimon-setup-td5803294.html

**Comment by bluss** [comment]
What I can see, this is an xmonad bug that shows when moving windows between monitors and the monitors have different aspect ratio. Something like that.

**Comment by bluss** [comment]
I installed xmonad, found a workaround.

KUPFER_WINDOW_POSITION=center_always ./kupfer-run --debug

This works with recent releases of kupfer. Always centering makes sense in the xmonad model I think.

**Comment by bluss** [comment]
`KUPFER_WINDOW_POSITION=` and `KUPFER_WINDOW_TYPE_HINT=` are knobs that are primarily there for troubleshooting and well debugging compatibility issues. It's pretty likely that these knobs will be made permanent and documented.

**Comment by jonhoo** [comment]
Wow, you really dug in! Yes, xmonad/xmonad#34 certainly seems related (and turns out I'm even already subscribed to it!).

Come to think of it, I've seen somewhat similar behavior in a couple of other applications. In particular, the gtk file chooser and the pinentry-gtk dialog. It seems to be connected to these kinds of "floating dialog" windows though. I haven't seen it anywhere else?

`KUPFER_WINDOW_POSITION=center_always` on the new branch helps a little. The behavior is now as follows:

 - Mouse on right monitor, active virtual desktop is on right monitor: **everything ok**
 - Mouse on left monitor, active virtual desktop is on left monitor: **everything ok**
 - Mouse on left monitor, active virtual desktop is on right monitor: 
   - First invocation: launcher appears on *right* monitor, but is stretched vertically and cut off horizontally.
    - Subsequent invocations: launcher appears on *left* monitor, correctly sized, but its top left corner is at the center of the screen.
 - Mouse on right monitor, active virtual desktop is on left monitor:
   - First invocation: launcher appears on *left* monitor, but is stretched *horizontally* and cut off vertically.
    - Subsequent invocations: launcher appears on *right* monitor, correctly sized, but its top left corner is at the center of the screen.
 - And then something *really* weird: if I now switch my active virtual desktop to the same monitor as the mouse, it appears correctly sized, but offset as described in the cases above.
 - If I then move my mouse to the *other* screen, *and* switch active virtual desktop to that monitor, the launcher is correctly sized and in the right place again.

**Comment by jonhoo** [comment]
For what it's worth, this problem does not occur when I have two 1920x1080 screens next to each other in the same environment (left screen still the same as in the previous setup, still using xmonad).

**Comment by bluss** [comment]
It's issue xmonad/xmonad/issues/5 that seems most relevant. To me it's clearly an xmonad bug and I'm passing it over to them.

If xmonad devs think we do something wrong, I'm curious to hear about that and what kupfer should do instead.

**Comment by jonhoo** [comment]
@bluss seems reasonable. Thanks for digging anyway!

**Comment by KarolBedkowski** [comment]
Upstream (xmonad) bugs are already closed. If this bug is still relevant please reopen this issue.
