### ISSUE TITLE
Kupfer can not search Rhythmbox songs until Rhythmbox starts

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#75]
### Actual Behavior
1. Set `include songs on top level` from plugin-preference

2. Quit Rhythmbox. Quit Kupfer and restart. 

3. Wait kupfer to load SongsSource....for me it is giving something like

```
D [kupfer.plugin.rhythmbox] RhythmboxSongsSource: Loaded items
D [kupfer.plugin.rhythmbox] RhythmboxSource: Loaded 4 items
```

3. Try search by songs names. It won't work. Navigate to Rhythbox->Songs..It's **empty**

### Expected Behavior

1. Kupfer should able to load previously stored song names from cache even when Rhythmbox is not running in the background. 

2. Pressing enter on song-object Kupfer should open Rhythmbox (only if it is not running) and starts playing the song.

### Environment
Kupfer Version: 317
Window Manager: Compiz (Unity)
Desktop Environment: Unity
Linux Distribution: Ubuntu 17.04

**Comment by bluss** [comment]
Thanks for the detailed design, fixed so that it keeps the old info around if not finding Rhythmbox on dbus. It works as expected for me now.

**Comment by bluss** [comment]
I think there are some problems with corner cases of Rhythmbox playback, mostly related to queue vs playlist playback.

Current behaviour when playing more than one song (comma trick or play whole artist/album) is to send the first song as play-uri and the rest as enqueue.

**Comment by khurshid-alam** [comment]
Thanks for fixing this. Now it works well both with albums and individual songs.
