### ISSUE TITLE
Use Rounded corners

### ISSUE THREAD

**Issue by bluss** [kupferlauncher/kupfer#83]
kupfer 319 has square window corners.

It's a library issue: Pygobject / Python GTK 3 bindings does not export the needed cairo types, so we can't use the relevant method [Gtk.Widget.shape_combine_region](https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/Widget.html#Gtk.Widget.shape_combine_region)

Potentially fixed in [this commit ](https://github.com/GNOME/pygobject/commit/7a3e4c005a6677ed7bf3ef807cd1a8487b0465de) which is in pygobject version 3.26 allegedly (Not yet released as of this writing).

**Comment by hugosenari** [comment]
Maybe we can use [this workaround](https://github.com/pychess/pychess/blob/master/lib/pychess/widgets/pydock/OverlayWindow.py#L42) while they don't release it with cairo.Region.

**Comment by dfyockey** [comment]
Kupfer Version: v321
Window Manager: Xfwm4
Desktop Environment: Xfce
Linux Distribution: Fedora 32

It took a lot of studying GTK+ 3 and a lot of poking at the code to get right, but... There be round corners here! :)

![Kupfer_with_Rounded_Corners_Screenshot_2021-04-15_09-40-25](https://user-images.githubusercontent.com/17618397/114883940-5aaed680-9dd3-11eb-8bb3-8a277d30f99a.png)

In the end, it only took a few changes in file `browser.py`. In the `initialize` method of `WindowController`, added the following comment and code just after the `self.window` definition:

    """
    Enable transparency specified in CSS, suggested by the answer at
    https://discourse.gnome.org/t/top-level-window-transparency-in-newer-versions-of-gtk/2210
    """
    screen = self.window.get_screen()
    visual = screen.get_rgba_visual()
    self.window.set_visual(visual)

And defined some attributes in the `#kupfer` class CSS:

    #kupfer {
        border-style: solid;
        border-width: 2px;
        border-radius: 0.6em;
        background-color: rgba(255, 255, 255, .9);
        border-color: green;
    }

Don't know if this is transferable to other DEs or WMs. Hope so.

**Comment by KarolBedkowski** [comment]
Rounded corners back in 323.

**Comment by bluss** [comment]
that's awesome @KarolBedkowski
