### ISSUE TITLE
Run (get output) does nothing

### ISSUE THREAD

**Issue by yisraeldov** [kupferlauncher/kupfer#88]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version:v208
Window Manager:awesome
Desktop Environment:
Linux Distribution:Ubuntu

### Actual Behaviour
When trying to run a command with the "Run (get output)" nothing happens.

* I use the `.` to go into test mode
* Enter a command, like `date`
* press `tab`
* Select `Run (get output)`
* Press `enter` 
* Nothing happens, the window just stays open

There is a plus sign next to the `Run (get output)` but I didn't see any mention of it in the docs.

### Expected Behaviour

The command will run and get the output.

**Comment by bluss** [comment]
Hi! I'm puzzled by this, it should work. However, Kupfer 208 is 5 years old, and we don't track its bugs here. Feel free to open issues found in Kupfer 3xy! Thanks.
