### ISSUE TITLE
Feature Request: Option to disable TextSouce from Top Level Search

### ISSUE THREAD

**Issue by hugosenari** [kupferlauncher/kupfer#90]
### Actual Behaviour
All TextSource are Top Level and user can't choose remove from top level without disable plugin.
- This can cause performance issues;
- If something goes wrong all search stop working (#73 related).

### Expected Behaviour
__When__ user enable any plugin with a TextSource
__Then__ add it in Catalog tab to be enabled/disabled from Top Level
__And__ add other way to access that TextSource:
- Maybe creating an action to search in non Top Level sources;
- Or just listing them in Sources and if user choose that source start searching using it

**Comment by bluss** [comment]
Yes. Since I've added ? to start free text, some plugins can use that and only produce results for ? prefix. I have a plugin in the works that uses it for firefox keyword search. I.e `?ddg search terms` would search duck duck go if there is a ddg keyword for it.

**Comment by hugosenari** [comment]
In this case plugin or kupfer must define this filter?

**Comment by bluss** [comment]
In this case the plugin itself defined that filter, so there was no resilience in that sense.

**Comment by KarolBedkowski** [comment]
Closing due inactivity.
