### ISSUE TITLE
What happened to Large Type

### ISSUE THREAD

**Issue by MageJohn** [kupferlauncher/kupfer#91]
I can find reference in the code to a Large Type action, however it seems to have been disabled. Why is this? Displaying a large message on the screen is potentially useful for a couple different things, so it would be nice to have.

**Comment by bluss** [comment]
It didn't work immediately in the GTK 3 port, so it wasn't ported. It can be revived but it needs some porting. What I remember is that it needs addressing for hidpi issues IMO, it can't use the previous hardcoded font size anymore.

**Comment by bluss** [comment]
Your request is valuable feedback as it is, too.

**Comment by SanskritFritz** [comment]
I loved the Large Type plugin too and would love to use it in Kupfer 3. I used it as a simple alarm, because notifications disappear in KDE without trace.

**Comment by MageJohn** [comment]
I see. Thanks for the reply! I'd look into doing the porting myself, but unfortunately I don't have the time at the moment due to exams.

**Comment by bluss** [comment]
The code is in kupfer/uiutils.py, reenable LargeType in kupfer/plugin/show_text.py. The code to set the font size requires porting.

**Comment by MageJohn** [comment]
Oh what the heck, I'll take a look anyway. :smile:

**Comment by MageJohn** [comment]
Okay, so I'll need to brush up on my GTK, and figure exactly how much I need to rewrite. I now need to go fix dinner, so it's not happening today. Any quick tips you can give on what you needed to do to port the other stuff would be awesome!

**Comment by bluss** [comment]
I think it is about constructing the PangoAttrList and its pieces correctly
