### ISSUE TITLE
[Feature suggestion] Option to use Zeitgeist as backend

### ISSUE THREAD

**Issue by lf-araujo** [kupferlauncher/kupfer#92]
Hello all,

I've been thinking, how old is Kupfer now, like 10 years or so? Congratulations!

This has been the most useful piece of software in my system for years now. Kupfer's catalog is really very useful, however the synctactic search provided by Zeitgeist returns more relevant results in my experience. Would it be possible to add support to Zeitgeist in Kupfer?

Keep up with the great work.

Thanks.

**Comment by bluss** [comment]
It's no longer relevant. I've chatted with some gnome devs and they don't consider zeitgeist to be relevant to current or future apps, so it's no use in trying to adopt it now. Back when Synaptic did it, looked a lot more reasonable then.
