### ISSUE TITLE
Gnote/Tomboy content decoration issue

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#93]
### Actual Behaviour
Search for Gnote and try to press right arrow key. Nothing happens. 

### Expected Behaviour
Notes should appear under Gnote/Tomboy.

**Comment by bluss** [comment]
I don't understand the exact problem, and I would prefer to not use grouping sources, it's a pretty bad solution. In fact.. what should it be grouped with?

**Comment by bluss** [comment]
I think that the most important here is to further clarify what the bug is, before we find a solution. Has the user configured which note program they want to use in the notes plugin's settings?

**Comment by khurshid-alam** [comment]
Ok. I realized I don't really need But can you at-least provide `appleaf_content_id = tm_pass = __kupfer_settings__["notes_application"]` so that I can view all notes from kupfer dropdown?

**Comment by bluss** [comment]
I get the feeling that there is some information left out. :Notes should already appear under the notes application you have configured. This may require a restart of Kupfer to take effect.

Is this not the case, the notes of Gnote don't appear under gnote? (If that's the app you select).

**Comment by bluss** [comment]
Existing definition of appleaf_content_id  https://github.com/kupferlauncher/kupfer/blob/master/kupfer/plugin/notes.py#L410-L412

**Comment by khurshid-alam** [comment]
> Is this not the case, the notes of Gnote don't appear under gnote? (If that's the app you select).

No. Instead they appear under generic name `Notes` .

**Comment by bluss** [comment]
Ok. Is this about Gnote? 

On my system it uses `gnote.desktop` making its identifier `gnote`. This may need expanding to other identifiers; it would help if you find the desktop file for your system.

> /usr/share/applications/gnote.desktop

**Comment by khurshid-alam** [comment]
Yes it's Gnote.

I have org.gnome.Gnote.desktop. The name is set properly there

```
[Desktop Entry]
Name=Gnote
```

I also notes-up (https://github.com/Philip-Scott/Notes-up) application installed which is using notes.desktop. It has 

```
[Desktop Entry]
Name=Notes
```
So far all of my Gnote's notes appearing under Notes. See here:
![screenshot from 2017-05-07 20-39-21](https://cloud.githubusercontent.com/assets/1333217/25782335/8f5e67c8-3366-11e7-95a8-0c6427896ad0.png)


No content appear under Gnote.
![screenshot from 2017-05-07 20-49-29](https://cloud.githubusercontent.com/assets/1333217/25782348/dcd2e290-3366-11e7-82c5-00d3b9fe856f.png)

**Comment by khurshid-alam** [comment]
I don't think it has anything to do with notes-up application using the name `Notes`. From the 1st screenshot you can see notes-up application appear below (the one with description `you markdown notebook`) and notes are **NOT** grouped under it.


I think Notes is just the name of the Source which is using Gnote's icon.

**Comment by bluss** [comment]
`org.gnome.Gnote.desktop` this is the information I was looking for, thank you. That explains why it does not decorate the gnote appleaf.

**Comment by bluss** [comment]
Current configuration will work look for a desktop file named `gnote.desktop` (should be case insensitive); that works with the packages on Fedora and Debian but we'll patch it so that it works on your system too.

**Comment by khurshid-alam** [comment]
Thanks. Happy to help.
