### ISSUE TITLE
Typing anything + ":" in free text mode tries to open a url  

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#94]
### Actual Behavior
1. type **.**
2. start typing something and then type a colon (**:**); i.e `note:`
3. Second pane automatically switches to open-url action
4. No other action available
5. With that I can **NOT** create note or task with colon in the name (i.e. `ProjectB: Make Blueprint `) 

### Expected Behavior
Kupfer should wait until user types `something + : + //,` then only it should show open-url action. 

### Environment
Kupfer Version: 319
Window Manager: Compiz
Desktop Environment: Unity 
Linux Distribution: Ubuntu 17.04

**Comment by Ryuno-Ki** [comment]
Well, according to [RFC2396](http://www.ietf.org/rfc/rfc2396.txt), the scheme ends with the colon (see section 3).

Take `mailto:` as an example. It does not have `//` after it.

**Comment by khurshid-alam** [comment]
There are whole lot of scheme like that. But they are not fit in this scenario. Nobody types mailto to email a person. And even if that the case we can change kupfer behavior to treat http:// and mailto: differently. The main problem is it doesn't provide any action for `+":" `other than open open url including mailto which is improper.

1. `:` be may present in anything your notes, tasks etc

2. It also happens in `non-free text `mode. That's the main issue here.

**Comment by bluss** [comment]
It is by design, sure — we don't know all URL schemes out there. mailto: is a pretty good example of an URL scheme it's actually designed for. `mailto:` is likely to be used by users since it's well known. Another common one is `magnet:` that doesn't use slashes.

If you type in `mailto:x` and down arrow into kupfer you can see some unfinished edges.. there's an URL type of object and a text type of object, yet the text has some URL like aspects. Some, but far from all, URL actions also find URLs in text objects.

For both mailto and magnets, it should be possible to paste them into Kupfer, and it is!

How do we indeed decide what type to give an object and should we care less about that maybe. Maybe the text ~/Docs is really a file, not just a text.

**Comment by bluss** [comment]
We can for example make sure that colon and then space does not make an URL.

**Comment by khurshid-alam** [comment]
Alright. I don't mind them as url but problem is these urlleaf has only action 'open-url'. For example lets say,

1. I copy a magnet link and paste to kupfer. 

2. Obviously the natural action would be 'open-url' which is fine.

3. But I may not want to open it but rather copy the link to gnote. But there is no way to do that as open-url is only default action.

Thoughts?

**Comment by bluss** [comment]
One can do that, paste or type an URL and press down arrow twice, then you have the text as a text object. Pasting a URL makes two objects, an UrlLeaf and a TextLeaf, with the Url always ranking higher. (Plugins can add more).

The more rambling thoughts are about having different types of objects and when we should have more types or less granular types. etc.

**Comment by khurshid-alam** [comment]
> Pasting a URL makes two objects, an UrlLeaf and a TextLeaf, with the Url always ranking higher. 

Yes. That's one way to do it. Can we make textleaf higher priority? Kupfer can not tell the difference between `"mailto:user@mail.com"` and "weather: sunny". Kupfer thinks all of them as url and hence give urlleaf higher priority. So it is creating some problem.

My suggestions are:

1. Like you suggested above:` We can for example make sure that colon and then space does not make an URL.`


OR


2. Hardcode common url-schemes (http://, ftp://, irc://, mailto:...etc) which can be opened with xdg-open.

**Comment by khurshid-alam** [comment]
@bluss Any news on this? I am ok with your proposed solution of colon+space.

**Comment by KarolBedkowski** [comment]
In last version url detection function was changed. URL should be better recognized.
