### ISSUE TITLE
Pidgin plugin ignores Facebook and Office Communicator Contacts

### ISSUE THREAD

**Issue by Alittlemurkling** [kupferlauncher/kupfer#96]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version: v307 onwards
Window Manager: bspwm
Desktop Environment: 
Linux Distribution: Arch Linux (current, kernel 4.11.4-1-ARCH)

### Actual Behaviour
Type the name of a Facebook/Office Communicator/Skype for Business contact, and you are presented with the 'Write to Command...' action. 

### Expected Behaviour
Type the name of the contact, and be presented with the Pidgin shortcut to start a conversation.

I have been dabbling with Python3 more at work and would like to take this one if it's a beginner friendly issue.

**Comment by khurshid-alam** [comment]
First check if 'show-offline' contacts option is enabled in kupfer plugin settings. The plugin only search for active contacts by default.

**Comment by KarolBedkowski** [comment]
For xmpp contact works fine.
I don't use skype/facebook/etc so I can't verify, but I don't see any reason why may not work.
