### ISSUE TITLE
Plugin: Firefox: Set bookmark title as description

### ISSUE THREAD

**Issue by khurshid-alam** [kupferlauncher/kupfer#98]
Firefox bookmark sets url as description. If many bookmarks have common search term, it is difficult to know which bookmark i am selecting. For long title it gets trimmed in the middle.

Here in the image I have started searching for `"issue"`......it shows two items.But I can neither remember the issue number nor the long htttp url. If it can show bookmark title it will easier for me to know which bookmark i am selecting for. Also for long description it should get trimmed at the end not at the middle.

![bookmark](https://i.imgur.com/LcLtIqd.png)

### Environment

Kupfer Version: 319
Window Manager: Compiz
Desktop Environment: Unity
Linux Distribution: Ubuntu 17.04

**Comment by Ryuno-Ki** [comment]
Based on [this question](https://www.quora.com/Are-there-any-way-to-access-my-bookmarks-in-Firefox-with-Python-Django-Flask) interesting resources will likely be:

* [Support article concerning Firefox profiles](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data)
* [Places Developer Guide on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Places_Developer_Guide)
* [Places.sqlite spec on Knowledge Base](http://kb.mozillazine.org/Places.sqlite)

**Comment by khurshid-alam** [comment]
@Ryuno-Ki  ? This is not about firefox bookmark, but rather how bookmark title should appear as description as url-leaf.

**Comment by Ryuno-Ki** [comment]
I understand that, @khurshid-alam.

I wanted to provide some research in case kupfer wants to tap into Firefox' way of saving bookmarks.
