### ISSUE TITLE
ENH: remember previous directory when cycling back to higher directory

### ISSUE THREAD

**Issue by eternalbit** [kupferlauncher/kupfer#99]
Don't know whether anyone else finds this inconvenient like I do:
When browsing through the directory structure (in order to get to a specific dir) I often (accidently) navigate one level too deep into the tree. I then cycle back to the previous level and press _left_ on the keyboard to go back ... this takes me one level higher but it also resets my previous choice, so I'd have to type (or select) again to get the desired dir.

Let's take this dir structure:
- /
  - stuff
    - stuffA
    - stuffB

I want to open _stuff_.
I type its name, it's highlighted and I press _right_ in order to see its contents (and thus confirm it's the right choice to open).
Now _stuffA_ is highlighted.
I press _left_ to go back to one level higher.
Now there's no directory highlighted and I'd have to type _stuff_ again to select/highlight and open it.

My proposal is:
- to have Kupfer remember the previously entered directory when cycling back to a higher level.
- to have Kupfer forget that previous directory as soon as something different is typed

**Comment by KarolBedkowski** [comment]
Should be already solved. Fill free to reopen if not.
